### PR TITLE
Report OverloadedException as a 429 in HTTP APIs (fixes #1233)

### LINKED ISSUE #1233: Catch OverloadedException in HTTP services and return 429
In the event rate limiting is used and an `org.apache.cassandra.exceptions.OverloadedException` is thrown it's currently not being handled and bubbling up as a 500. Instead this exception should be caught and a [429](https://httpstatuses.com/429) should be returned instead. This is most prevalent in the Docs API due to the number of queries it makes per request but any of our services could have the same problem. 

```java
ERROR [jersey-server-managed-async-executor-7] 2021-09-08 17:48:21,780 ErrorHandler.java:59 - Error when executing request
 java.util.concurrent.CompletionException: org.apache.cassandra.exceptions.OverloadedException: Rate limit reached
 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
 	at io.stargate.db.datastore.PersistenceBackedDataStore.batch(PersistenceBackedDataStore.java:190)
 	at io.stargate.db.datastore.PersistenceBackedDataStore.batch(PersistenceBackedDataStore.java:179)
 	at io.stargate.db.query.AsyncQueryExecutor.batch(AsyncQueryExecutor.java:104)
 	at io.stargate.db.query.AsyncQueryExecutor.batch(AsyncQueryExecutor.java:82)
 	at io.stargate.web.docsapi.dao.DocumentDB.executeBatch(DocumentDB.java:391)
 	at io.stargate.web.docsapi.dao.DocumentDB.deleteThenInsertBatch(DocumentDB.java:612)
 	at io.stargate.web.docsapi.service.DocumentService.putAtPath(DocumentService.java:526)
 	at io.stargate.web.docsapi.resources.DocumentResourceV2.lambda$postDoc$0(DocumentResourceV2.java:147)
 	at io.stargate.web.docsapi.resources.DocumentResourceV2.handle(DocumentResourceV2.java:624)
 	at io.stargate.web.docsapi.resources.DocumentResourceV2.postDoc(DocumentResourceV2.java:137)
```

### PR DESCRIPTION
**Pull request by olim7t**
**What this PR does**:
Handle Cassandra's `OverloadedException` specially in HTTP APIs in order to return a 429 response code.

**Which issue(s) this PR fixes**:
Fixes #1233

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] ~Documentation added/updated~

### CODE REVIEW

File: graphqlapi/src/main/java/io/stargate/graphql/schema/CassandraFetcherExceptionHandler.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+public class CassandraFetcherExceptionHandler extends SimpleDataFetcherExceptionHandler {
+
+  public static CassandraFetcherExceptionHandler INSTANCE = new CassandraFetcherExceptionHandler();
+
+  @Override
+  public DataFetcherExceptionHandlerResult onException(
+      DataFetcherExceptionHandlerParameters handlerParameters) {
+    if (handlerParameters.getException() instanceof OverloadedException) {
+      StargateGraphqlContext context = handlerParameters.getDataFetchingEnvironment().getContext();
+      context.setOverloaded();
```
Comment (olim7t) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/CassandraFetcherExceptionHandler.java:33]: `GraphqlResourceBase` checks this flag before completing the response.
This is the only way I have found to propagate the information. If I rethrow, the GraphQL library has a special catch block that will still wrap it into a GraphQL error.

File: restapi/src/main/java/io/stargate/web/resources/RequestHandler.java [hunk 2]
```diff
@@ -45,6 +46,13 @@ public static Response handle(Callable<Response> action) {
                   "Resource not found: " + nfe.getMessage(),
                   Response.Status.NOT_FOUND.getStatusCode()))
           .build();
+    } catch (OverloadedException e) {
+      logger.info("Overloaded", e);
```
Comment (olim7t) [inline restapi/src/main/java/io/stargate/web/resources/RequestHandler.java:50]: Duplicated to mimic the existing code, but logging errors at info feels weird.

**Review by olim7t — COMMENTED** [review]
This is hard to test since we would have to reproduce the overload error.

I've checked GraphQL manually by temporarily modifying the fetcher code to throw the exception, I'll do the same for the other APIs.

File: restapi/src/main/java/io/stargate/web/resources/RequestHandler.java (hunk 2 above)
Comment (ivansenic) [reply restapi/src/main/java/io/stargate/web/resources/RequestHandler.java:50]: True.. Just imagine the size of the log once we are hitting the `OverloadedException`.. Let's log only the important stuff, something we don't know why is it happening, or?

File: graphqlapi/src/main/java/io/stargate/graphql/web/resources/GraphqlResourceBase.java [hunk 3]
```diff
@@ -341,11 +341,21 @@ protected static void executeAsync(
...
     graphql
         .executeAsync(input)
-        .thenApply(result -> asyncResponse.resume(result.toSpecification()))
+        .thenApply(
+            result -> {
+              StargateGraphqlContext context = (StargateGraphqlContext) input.getContext();
+              if (context.isOverloaded()) {
+                replyWithGraphqlError(
+                    Status.TOO_MANY_REQUESTS, "Database is overloaded", asyncResponse);
+                return true;
```
Comment (ivansenic) [inline graphqlapi/src/main/java/io/stargate/graphql/web/resources/GraphqlResourceBase.java:350]: what's the meaning of this `true` here? shouldn't you return `boolean` as the result of the `replyWithGraphqlError`?

**Review by ivansenic — APPROVED** [review]
Looks good, have a look on the comments..

File: restapi/src/main/java/io/stargate/web/docsapi/resources/error/ErrorHandler.java [hunk 4]
```diff
@@ -48,6 +49,12 @@ public Response apply(Throwable throwable) {
                   "Role unauthorized for operation: " + throwable.getMessage(),
                   Response.Status.UNAUTHORIZED.getStatusCode()))
           .build();
+    } else if (throwable instanceof OverloadedException) {
```
Comment (tomekl007) [inline restapi/src/main/java/io/stargate/web/docsapi/resources/error/ErrorHandler.java:52]: should this be handled for gRPC as well?

File: restapi/src/main/java/io/stargate/web/resources/RequestHandler.java (hunk 2 above)
Comment (olim7t) [reply restapi/src/main/java/io/stargate/web/resources/RequestHandler.java:50]: You're right, this is definitely a bad idea, removing it.

File: graphqlapi/src/main/java/io/stargate/graphql/web/resources/GraphqlResourceBase.java (hunk 3 above)
Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/web/resources/GraphqlResourceBase.java:350]: It's just to respect the return type of the lambda, we don't do anything with the returned value. This was kind of hidden previously when the lambda was just calling `asyncResponse.resume`.

I'm changing the return type to `Void` to clarify things.

File: restapi/src/main/java/io/stargate/web/docsapi/resources/error/ErrorHandler.java (hunk 4 above)
Comment (olim7t) [reply restapi/src/main/java/io/stargate/web/docsapi/resources/error/ErrorHandler.java:52]: This PR is about HTTP APIs.

But yes, gRPC should also handle `Overloaded` in a protocol-specific way (most likely an error status).

**Comment by tatu-at-datastax** [comment]
Quick note: this will help with #1279 a bit too -- will probably want to add to exception handler being added in this PR.

**Review by dougwettlaufer — APPROVED** [review]

File: graphqlapi/src/main/java/io/stargate/graphql/web/StargateGraphqlContext.java [hunk 5]
```diff
@@ -53,6 +53,8 @@
   // For more information.
   private final BatchContext batchContext = new BatchContext();
 
+  private volatile boolean overloaded;
```
Comment (tatu-at-datastax) [inline graphqlapi/src/main/java/io/stargate/graphql/web/StargateGraphqlContext.java:56]: Maybe add brief Javadoc here (or on setter) mentioning reason; flag to indicate that overload fail (429) was received during fetching.

Comment (ivansenic) [reply graphqlapi/src/main/java/io/stargate/graphql/web/StargateGraphqlContext.java:56]: I can not find this new `volatile` anywhere, is this removed or what s going on?

Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/web/StargateGraphqlContext.java:57]: Volatile is enough, we just need to guarantee that if the value was changed, the change will be visible.

We don't need synchronization because:
* the only thing writers can do is set the value to `true`. So even if this happens multiple times, they don't race with each other. (PS: it can happen multiple times, if a GraphQL payload contains multiple operations and more than one `OverloadedException` occurs)
* we read back the value after the execution of the payload (`GraphqlResourceBase`). All exception handlers are guaranteed to have run at that point, since their output is part of the response.
