### PR TITLE
Fix prepared statement handling in ValidatingDataStore

### LINKED ISSUE #1026: Validating data store should compare against externalQueryString
Currently the validating data store compares against the prepared query, which is wrong, because it should compare against the query defined by the user. The placeholder `?` should be used in the asserting query only for the values that are directly binded after the preparation.

### PR DESCRIPTION
**Pull request by dimas-b**
Fixes #1026

### CODE REVIEW

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java [hunk 1]
```diff
@@ -96,22 +96,36 @@ public boolean supportsLoggedBatches() {
...
       BoundQuery query, UnaryOperator<Parameters> parametersModifier) {
-    ExpectedExecution execution;
-    if (query instanceof ExpectedExecution) {
-      execution = (ExpectedExecution) query;
-    } else {
-      Prepared<?> prepared = (Prepared<?>) prepare(query.source().query()).join();
-      execution = (ExpectedExecution) prepared.bindValues(query.values());
+    Optional<MD5Digest> preparedId = query.source().query().preparedId();
+    if (!preparedId.isPresent()) {
+      preparedId = prepare(query.source().query()).join().preparedId();
```
Comment (tomekl007) [inline restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:114]: why do we use a blocking operation (`join`) in the method that is non-blocking (returns `CompletableFuture<ResultSet>`)? Shouldn't it be fixed

Comment (tomekl007) [inline restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:114]: why do we use a blocking operation (`join`) in the method that is non-blocking (returns `CompletableFuture<ResultSet>`)? Shouldn't it be fixed?

File: restapi/src/test/java/io/stargate/web/docsapi/service/query/search/resolver/filter/impl/InMemoryCandidatesFilterTest.java [hunk 2]
```diff
@@ -199,7 +199,11 @@ public void fixedPath() {
           withQuery(
                   TABLE,
                   "SELECT key, leaf, text_value, dbl_value, bool_value, p0, p1, WRITETIME(leaf) FROM %s WHERE p0 = ? AND leaf = ? AND p1 = ? AND key = ? LIMIT ? ALLOW FILTERING",
-                  documentId)
+                  "field",
```
Comment (tomekl007) [inline restapi/src/test/java/io/stargate/web/docsapi/service/query/search/resolver/filter/impl/InMemoryCandidatesFilterTest.java:202]: why do we change the `documentApi` tests in the ticket that is fixing data store API? Shouldn't those changes be separated?

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java [hunk 3]
```diff
@@ -96,22 +96,36 @@ public boolean supportsLoggedBatches() {
...
-    prepared.add(p);
-    return CompletableFuture.completedFuture(p);
+    // Generate unique IDs for each `prepare` call to validate that all prepared statements get
+    // executed.
+    ByteBuffer buffer = ByteBuffer.allocate(Integer.BYTES);
+    buffer.putInt(preparedIdSeq.incrementAndGet());
+    MD5Digest preparedId = MD5Digest.wrap(buffer.array());
+    Query<B> queryWithId = query.withPreparedId(preparedId);
+    prepared.computeIfAbsent(preparedId, p -> new Prepared<>(queryWithId));
+    return CompletableFuture.completedFuture(queryWithId);
```
Comment (tomekl007) [inline restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:106]: nit: maybe extract this logic to a separate method with a name stating the intent clearly. (emphasize more what's in the comment)

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java [hunk 4]
```diff
@@ -223,9 +210,11 @@ public B bindValues(List<TypedValue> values) {
       ExpectedExecution exec = new ExpectedExecution(this, expectation);
       expectedExecutions.add(exec);
       bound = true;
-      this.source = new BoundQuery.Source<>(query, values);
-      //noinspection unchecked
-      return (B) exec;
+      return exec;
+    }
+
+    public boolean hasId(MD5Digest preparedId) {
```
Comment (tomekl007) [inline restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:216]: where this method is called? I don't see any invocation.

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java (hunk 1 above)
Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:114]: The whole call chain in this case is owned by this test class. The `prepare` call returns a "complete" future in all cases.

However, I can probably refactor this for the sake of clarity.

Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:114]: duplicate comment?... resolving

File: restapi/src/test/java/io/stargate/web/docsapi/service/query/search/resolver/filter/impl/InMemoryCandidatesFilterTest.java (hunk 2 above)
Comment (dimas-b) [reply restapi/src/test/java/io/stargate/web/docsapi/service/query/search/resolver/filter/impl/InMemoryCandidatesFilterTest.java:202]: These test were incorrect. They did not validate bound variables because the bugs in `ValidatingDataStore` did not make it possible. After fixing `ValidatingDataStore` I re-added bound variable validation to the tests.

`withQuery(...)` methods are meant to match both the query text and specific parameter values so that the test code could provide different result sets for different parameters.

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java (hunk 4 above)
Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java:216]: good catch, thx! It is not used... leftover from a previous iteration. will remove.

Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java]: removed in the refactored code (force-pushed)

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java (hunk 3 above)
Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java]: refactored (force-pushed)

File: restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java (hunk 1 above)
Comment (dimas-b) [reply restapi/src/test/java/io/stargate/db/datastore/ValidatingDataStore.java]: refactored (force-pushed)

**Review by ivansenic — APPROVED** [review]
That's what I am talking about :partying_face: Thanks @dimas-b for the effort, I am gonna merge asap so I can rebase tests it in the #1080

**Review by tomekl007 — APPROVED** [review]
