### PR TITLE
Fix for #2166 -> enhanced logging for the public grpc API exceptions

### LINKED ISSUE #2166: gRPC service exception handlers should log exceptions
We should at least log the exceptions that's considered server-side errors.. A good example of those exists already in the:

```
io.stargate.sgv2.restsvc.impl.GrpcExceptionMapper#grpcResponseAndLog
```

A set of status codes that do not have to be logged: `OK|CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|UNAUTHENTICATED|PERMISSION_DENIED`

Because there is no logging, the original exceptions are lost.

### PR DESCRIPTION
**Pull request by versaurabh**
**What this PR does**:
1. This PR logs additional details for the exceptions in the public gRPC API, the additional details are `status code and the stacktrace` 
2. Excludes the detailed logging for status codes `OK|CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|UNAUTHENTICATED|PERMISSION_DENIED`
3. For the `v2.0.0` gRPC bridge, there would be a separate PR

**Which issue(s) this PR fixes**:
Fixes #2166 

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [X] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 1]
```diff
@@ -61,8 +61,10 @@ public void handleException(Throwable throwable) {
       handleException(throwable.getCause());
     } else if (throwable instanceof StatusException
         || throwable instanceof StatusRuntimeException) {
+      LOG.error(getErrorMessage(null, throwable));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:64]: we should always include the exception in the log:

`LOG.error(message, exception)`

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 2]
```diff
@@ -72,11 +74,34 @@ public void handleException(Throwable throwable) {
...
+      if (throwable instanceof StatusException) {
+        status = ((StatusException) throwable).getStatus();
+      } else if (throwable instanceof StatusRuntimeException) {
+        status = ((StatusRuntimeException) throwable).getStatus();
+      } else {
+        status = Status.UNKNOWN;
+      }
+    }
+
+    return status.withDescription(throwable.getMessage()).withCause(throwable).toString();
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:96]: what kind of a message this gives, can you post an example? Maybe this is too much, we could have simpler messages not depending on the status..

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 3]
```diff
@@ -94,9 +120,11 @@ private void handlePersistenceException(PersistenceException pe) {
         handleUnavailable((UnavailableException) pe);
         break;
       case OVERLOADED:
+        LOG.error(getErrorMessage(Status.RESOURCE_EXHAUSTED, pe));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:123]: I am not sure we should log this one, it can occur when the client does not have a proper request rate limit setup..

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 4]
```diff
@@ -134,6 +163,7 @@ private void handlePersistenceException(PersistenceException pe) {
   }
 
   private void handleUnavailable(UnavailableException ue) {
+    LOG.error(getErrorMessage(Status.DEADLINE_EXCEEDED, ue));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:166]: logged status is not the same as the one reported back?

**Review by ivansenic — CHANGES_REQUESTED** [review]
Added few comments, maybe @tatu-at-datastax can also have a look here.. Anyhow, we need the same for the `bridge` `ExceptionHandler`, let's add this in a separate PR once this is merged..

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java (hunk 2 above)
Comment (versaurabh) [reply grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:96]: hi @ivansenic the error log looks as below 

```
ERROR [mainIOThread-0] 2022-11-07 16:53:07,799 ExceptionHandler.java:273 - Status{code=ALREADY_EXISTS, description=Cannot add existing keyspace "test", cause=org.apache.cassandra.stargate.exceptions.AlreadyExistsException: Cannot add existing keyspace "test"
	at io.stargate.db.dse.impl.Conversion.toExternal(Conversion.java:450)
	at io.stargate.db.dse.impl.Conversion.convertInternalException(Conversion.java:589)
	at io.stargate.db.dse.impl.DsePersistence$DseConnection.convertExceptionWithWarnings(DsePersistence.java:611)
	at io.stargate.db.dse.impl.DsePersistence$DseConnection.lambda$executeRequest$3(DsePersistence.java:591)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onError(SingleDoFinally.java:79)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:48)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:69)
	at io.reactivex.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:68)
	at io.reactivex.internal.operators.completable.CompletableEmpty.subscribeActual(CompletableEmpty.java:27)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.single.SingleDelayWithCompletable.subscribeActual(SingleDelayWithCompletable.java:36)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at org.apache.cassandra.utils.flow.RxThreads$1SubscribeOn.lambda$subscribeActual$0(RxThreads.java:51)
	at org.apache.cassandra.concurrent.TPCRunnable.run(TPCRunnable.java:101)
	at org.apache.cassandra.concurrent.IOScheduler$PooledTaskWorker.run(IOScheduler.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.cassandra.utils.concurrent.InlinedThreadLocalThread.run(InlinedThreadLocalThread.java:251)
	at org.apache.cassandra.concurrent.IOThread.run(IOThread.java:46)
	Suppressed: org.apache.cassandra.exceptions.AlreadyExistsException: Cannot add existing keyspace "test"
		at org.apache.cassandra.cql3.statements.schema.CreateKeyspaceStatement.apply(CreateKeyspaceStatement.java:71)
		at org.apache.cassandra.schema.SchemaManager.apply(SchemaManager.java:818)
		at org.apache.cassandra.schema.MigrationManager.lambda$applyAndAnnounce$8(MigrationManager.java:385)
		at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
		... 26 more
```

- we could have the log as `ERROR [mainIOThread-0] 2022-11-07 16:53:07,799 ExceptionHandler.java:273 - Status{code=ALREADY_EXISTS, description=Cannot add existing keyspace "test"}` without the `cause` section?
- I had put in the status codes for easier correlation to client response and server exception

Comment (tatu-at-datastax) [reply grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:96]: Hmmmmh. I don't think we want stack traces for this specific example, as it's client error? We'd only want things that fail due to something server does wrong or doesn't handle. But not when caller tries to do something they cannot.

**Comment by tatu-at-datastax** [comment]
I think we need to discuss this: I am not sure we want to log all the cases, and in some cases may not want to add stack trace.

My particular concerns are:

1. Timeouts we get: common and typically nothing we can do -- we do want to catch these via metrics, but probably not create ERROR log entries
2. Operations that fail because client is trying to do something they cannot: get info on typoed keyspace etc; attempts to delete table without access etc. These are reported as client-side failures and are not error cases by server

A related question is whether we could/should keep by-status-code metrics of gRPC responses. This could be useful in investigating issues.

Another possibility wrt logging is that some failure cases could be WARNs instead of ERRORs.

**Comment by versaurabh** [comment]
Hi @tatu-at-datastax @ivansenic let me list down the exceptions and segregate them into client and server side and then log only the server side exceptions, sounds like a good next step?

**Comment by ivansenic** [comment]
I guess if you two @versaurabh @tatu-at-datastax would sync on this, as Tatu has a very good overview on what should be logged and what not.. Just don't forget to updated the bridge exception handling as well.

**Comment by tatu-at-datastax** [comment]
> Hi @tatu-at-datastax @ivansenic let me list down the exceptions and segregate them into client and server side and then log only the server side exceptions, sounds like a good next step?

Yes!

**Comment by tatu-at-datastax** [comment]
> I guess if you two @versaurabh @tatu-at-datastax would sync on this, as Tatu has a very good overview on what should be logged and what not.. Just don't forget to updated the bridge exception handling as well.

+1. We synced up and have an idea of what to log, and where to include stack traces. Obviously need to tweak choices based on what we see, but I think we can get ok baseline.

Also will create separate issue for Bridge-service handling; this one is for gRPC service only (will change description)

**Comment by versaurabh** [comment]
> > I guess if you two @versaurabh @tatu-at-datastax would sync on this, as Tatu has a very good overview on what should be logged and what not.. Just don't forget to updated the bridge exception handling as well.
> 
> +1. We synced up and have an idea of what to log, and where to include stack traces. Obviously need to tweak choices based on what we see, but I think we can get ok baseline.
> 
> Also will create separate issue for Bridge-service handling; this one is for gRPC service only (will change description)

Hi @tatu-at-datastax @ivansenic 
Post discussion, below is the list of statuses being logged and whether stacktrace being logged or not for the logged status exceptions. 

- The stacktrace is logged as of now for the exceptions that arise from the gRPC API layer (and not persistence, etc.)

|  | Logged | Not Logged |
| ------------- | ------------- | ------------- |
| **Stacktrace logged**  |StatusException, StatusRuntimeException, UnhandledClientException  | ---NA--- |
| **Stacktrace not logged**  |  SERVER_ERROR, PROTOCOL_ERROR, UNPREPARED, TRUNCATE_ERROR, CDC_WRITE_FAILURE, UNAVAILABLE, IS_BOOTSTRAPPING, WRITE_TIMEOUT, READ_TIMEOUT, READ_FAILURE, FUNCTION_FAILURE, WRITE_FAILURE, CAS_WRITE_UNKNOWN, CONFIG_ERROR   | INVALID, SYNTAX_ERROR, BAD_CREDENTIALS, OVERLOADED, UNAUTHORIZED, ALREADY_EXISTS |

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 5]
```diff
@@ -61,8 +61,10 @@ public void handleException(Throwable throwable) {
       handleException(throwable.getCause());
     } else if (throwable instanceof StatusException
         || throwable instanceof StatusRuntimeException) {
+      LOG.error(getErrorMessage(null, throwable, true));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:64]: but wait the error is still not given as a second parameter to the `LOG.error()`

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 6]
```diff
@@ -72,11 +74,37 @@ public void handleException(Throwable throwable) {
...
+  /**
+   * @param status
+   * @param throwable
+   * @return generic error message for gRPC exceptions using gRPC Status and Exception thrown. If
+   *     the status is null and throwable is a {@link StatusException} or {@link
+   *     StatusRuntimeException} it extracts its status. If the status is null and throwable is
+   *     another instance type, it will have the status code {@code Status.UNKNOWN}.
+   */
+  protected String getErrorMessage(
+      @Nullable Status status, @Nonnull Throwable throwable, boolean logStackTrace) {
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:86]: remove logStackTrace and add exception as the parameter to the log, then the stacktrace will be logged by the logger.

**Review by ivansenic — CHANGES_REQUESTED** [review]

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 7]
```diff
@@ -97,6 +124,7 @@ private void handlePersistenceException(PersistenceException pe) {
         onError(Status.RESOURCE_EXHAUSTED, pe);
         break;
       case IS_BOOTSTRAPPING:
+        LOG.error(getErrorMessage(Status.UNAVAILABLE, pe), pe);
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:127]: here we can omit the stacktrace, wdyt @tatu-at-datastax ?

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 8]
```diff
@@ -121,6 +149,7 @@ private void handlePersistenceException(PersistenceException pe) {
         onError(Status.PERMISSION_DENIED, pe);
         break;
       case CONFIG_ERROR:
+        LOG.error(getErrorMessage(Status.FAILED_PRECONDITION, pe));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:152]: same here?

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 9]
```diff
@@ -147,6 +177,7 @@ private void handleUnavailable(UnavailableException ue) {
   }
 
   private void handleWriteTimeout(WriteTimeoutException wte) {
+    LOG.error(getErrorMessage(Status.DEADLINE_EXCEEDED, wte), wte);
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:180]: not sure about timeouts @tatu-at-datastax

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 10]
```diff
@@ -161,6 +192,7 @@ private void handleWriteTimeout(WriteTimeoutException wte) {
   }
 
   private void handleReadTimeout(ReadTimeoutException rte) {
+    LOG.error(getErrorMessage(Status.DEADLINE_EXCEEDED, rte), rte);
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:195]: here as well..

**Review by ivansenic — APPROVED** [review]
So I marked 4 places where I am not sure if stacktrace should be logged.. If you ask me I would log it everywhere.. I am passing over to @tatu-at-datastax for final decision.

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java (hunk 3 above)
Comment (tatu-at-datastax) [reply grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java]: Hmmh. I can see how this could be problematic.

Let's remove logging here: we still get response code metrics (503 or something).

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java (hunk 4 above)
Comment (tatu-at-datastax) [reply grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java]: Is there a better `Status` code to use?

**Comment by tatu-at-datastax** [comment]
> > > I guess if you two @versaurabh @tatu-at-datastax would sync on this, as Tatu has a very good overview on what should be logged and what not.. Just don't forget to updated the bridge exception handling as well.
> > 
> > 
> > +1. We synced up and have an idea of what to log, and where to include stack traces. Obviously need to tweak choices based on what we see, but I think we can get ok baseline.
> > Also will create separate issue for Bridge-service handling; this one is for gRPC service only (will change description)
> 
> Hi @tatu-at-datastax @ivansenic Post discussion, below is the list of statuses being logged and whether stacktrace being logged or not for the logged status exceptions.
> 
> * The stacktrace is logged as of now for the exceptions that arise from the gRPC API layer (and not persistence, etc.)
> 
> Logged	Not Logged
> **Stacktrace logged**	StatusException, StatusRuntimeException, UnhandledClientException	---NA---
> **Stacktrace not logged**	SERVER_ERROR, PROTOCOL_ERROR, UNPREPARED, TRUNCATE_ERROR, CDC_WRITE_FAILURE, UNAVAILABLE, IS_BOOTSTRAPPING, WRITE_TIMEOUT, READ_TIMEOUT, READ_FAILURE, FUNCTION_FAILURE, WRITE_FAILURE, CAS_WRITE_UNKNOWN, CONFIG_ERROR	INVALID, SYNTAX_ERROR, BAD_CREDENTIALS, OVERLOADED, UNAUTHORIZED, ALREADY_EXISTS

Hmmh. I thought we would log stack trace for: SERVER_ERROR, PROTOCOL_ERROR, CAS_WRITE_UNKNOWN, CONFIG_ERROR. So failures that occur on server, not as a result of something client did wrong. The rest look good.

**Comment by versaurabh** [comment]
> CONFIG_ERROR



> > > > I guess if you two @versaurabh @tatu-at-datastax would sync on this, as Tatu has a very good overview on what should be logged and what not.. Just don't forget to updated the bridge exception handling as well.
> > > 
> > > 
> > > +1. We synced up and have an idea of what to log, and where to include stack traces. Obviously need to tweak choices based on what we see, but I think we can get ok baseline.
> > > Also will create separate issue for Bridge-service handling; this one is for gRPC service only (will change description)
> > 
> > 
> > Hi @tatu-at-datastax @ivansenic Post discussion, below is the list of statuses being logged and whether stacktrace being logged or not for the logged status exceptions.
> > 
> > * The stacktrace is logged as of now for the exceptions that arise from the gRPC API layer (and not persistence, etc.)
> > 
> > Logged	Not Logged
> > **Stacktrace logged**	StatusException, StatusRuntimeException, UnhandledClientException	---NA---
> > **Stacktrace not logged**	SERVER_ERROR, PROTOCOL_ERROR, UNPREPARED, TRUNCATE_ERROR, CDC_WRITE_FAILURE, UNAVAILABLE, IS_BOOTSTRAPPING, WRITE_TIMEOUT, READ_TIMEOUT, READ_FAILURE, FUNCTION_FAILURE, WRITE_FAILURE, CAS_WRITE_UNKNOWN, CONFIG_ERROR	INVALID, SYNTAX_ERROR, BAD_CREDENTIALS, OVERLOADED, UNAUTHORIZED, ALREADY_EXISTS
> 
> Hmmh. I thought we would log stack trace for: SERVER_ERROR, PROTOCOL_ERROR, CAS_WRITE_UNKNOWN, CONFIG_ERROR. So failures that occur on server, not as a result of something client did wrong. The rest look good.

Hi @tatu-at-datastax logging stacktrace for CONFIG_ERROR as well, with this we would be logging stacktrace for all the exceptions post discussion with @ivansenic

File: grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java [hunk 11]
```diff
@@ -134,6 +162,7 @@ private void handlePersistenceException(PersistenceException pe) {
   }
 
   private void handleUnavailable(UnavailableException ue) {
+    LOG.error(getErrorMessage(Status.UNAVAILABLE, ue));
```
Comment (ivansenic) [inline grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java:165]: so here I would add the stack, I know status is UNAVAILABLE, but this is comming from the UnavailableException and we need to know what was unavailable. Actually we could print it also for the other case when UNAVAILABLE is sent bac as well, this bootsrapping situation that should actually never happen.

Comment (versaurabh) [reply grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java]: final impl matrix logging stacktrace for server errors @ivansenic @tatu-at-datastax 

|  | Logged | Not Logged |
| ------------- | ------------- | ------------- |
| **Stacktrace logged**  |StatusException, StatusRuntimeException, UnhandledClientException, SERVER_ERROR, PROTOCOL_ERROR, UNPREPARED, CAS_WRITE_UNKNOWN, CONFIG_ERROR, TRUNCATE_ERROR, CDC_WRITE_FAILURE, READ_FAILURE, FUNCTION_FAILURE, WRITE_FAILURE, UNAVAILABLE, IS_BOOTSTRAPPING  | ---NA--- |
| **Stacktrace not logged**  | WRITE_TIMEOUT, READ_TIMEOUT | INVALID, SYNTAX_ERROR, BAD_CREDENTIALS, OVERLOADED, UNAUTHORIZED, ALREADY_EXISTS |
