### PR TITLE
Second part of fix to #2179: handle "executeQueryWithSchema()" too

### LINKED ISSUE #2179: Bridge service is not handling runtime exceptions
Bridge service currently silently ignores the `RuntimeExceptions`, if they occur in the methods that are not handled with the `MessageHandlers`. Basically:

* `executeQueryWithSchema`
* `describeKeyspace`

The proper try/catch must be included, so that any runtime exception is handled. Current situation is that client side hangs, because observer on the server side is not informed on the error.

We need to catch that hang in test first. This can be easily done, mock the `Persistence` and for example throw exception on `persistence.decorateKeyspaceName`..

In addition to this, these exceptions should be logged. Also we should log possibly all the exceptions that we catch in the `io.stargate.bridge.service.ExceptionHandler`, which is not done right now.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds graceful handling of RuntimeExceptions too for "BridgeService.executeQueryWithSchema()"

**Which issue(s) this PR fixes**:
Fixes #2179

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: bridge/src/main/java/io/stargate/bridge/service/BridgeService.java [hunk 1]
```diff
@@ -93,9 +93,17 @@ public void executeQueryWithSchema(
...
+    Keyspace keyspace;
+
+    try {
+      decoratedName =
+          persistence.decorateKeyspaceName(keyspaceName, BridgeService.HEADERS_KEY.get());
+      keyspace = persistence.schema().keyspace(decoratedName);
+    } catch (Throwable t) {
+      new ExceptionHandler(responseObserver).handleException(t);
+      return;
+    }
```
Comment (ivansenic) [inline bridge/src/main/java/io/stargate/bridge/service/BridgeService.java:106]: I am gonna include the whole method with try.catch, no need just to protect that first part.

**Review by ivansenic — APPROVED** [review]

File: bridge/src/main/java/io/stargate/bridge/service/BridgeService.java (hunk 1 above)
Comment (ivansenic) [reply bridge/src/main/java/io/stargate/bridge/service/BridgeService.java:106]: Most likely also needs rebase after #2190 is merged
