### PR TITLE
Fix #1276: handle Jackson-originating parsing fails more gracefully

### LINKED ISSUE #1276: Log JsonSurfer/Jackson parsing issues without stack trace
As part of reducing log noise, I see a lot of noise from tests for handling of invalid JSON request content: in addition to responding with suitable error code code also logs exceptions. This is partly due to JsonSurfer exposing general-purpose `Exception` (since it supports multiple json libraries). Entries look like:

```
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-24 17:48:59,368 ProcessRunner.java:78 - stargate6-0> ERROR [jersey-server-managed-async-executor-30] 2021-09-24 17:48:59,367 DocsShredder.java:205 - Error occurred during JSON read
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-24 17:48:59,368 ProcessRunner.java:78 - stargate6-0> java.lang.RuntimeException: Unexpected end-of-input within/between Object entries
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-24 17:48:59,368 ProcessRunner.java:78 - stargate6-0>  at [Source: (String)"{"malformed":"; line: 1, column: 14]
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-24 17:48:59,368 ProcessRunner.java:78 - stargate6-0> 	at io.stargate.web.docsapi.exception.RuntimeExceptionPassHandlingStrategy.handleParsingException(RuntimeExceptionPassHandlingStrategy.java:14)
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-24 17:48:59,368 ProcessRunner.java:78 - stargate6-0> 	at org.jsfr.json.JacksonParser$JacksonResumableParser.parse(JacksonParser.java:143)
St
... [long stack trace]....
```

In these particular cases where we know the exception type (`JsonProcessingException` as the cause) we could add specific handling and drop stack trace, leaving stack trace only for truly unexpected issues (getting invalid JSON from client is not really exceptional in that sense).

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds bit more explicit handling for JSON parsing fails for Document API, by wrapping jackson's exceptions at JsonSurfer handler, then taking bit different action: logging only at WARN (or maybe in future, not at all?), and not adding stack trace.
Leaving ERROR/stack-trace for "unknown" fails.

**Which issue(s) this PR fixes**:
Fixes #1276

**Checklist**

- [x] Changes manually tested - checked that log output changed to omit Stack trace for cases found
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated

Changed output on C*4.0 CI logs:

```
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-27 15:56:25,902 ProcessRunner.java:78 - stargate6-0> WARN  [jersey-server-managed-async-executor-31] 2021-09-27 15:56:25,902 DocsShredder.java:208 - Invalid JSON payload encountered during JSON read (com.fasterxml.jackson.core.io.JsonEOFException): Unexpected end-of-input within/between Object entries
Step #4 - "cassandra-4.0": INFO  [Exec Stream Pumper] 2021-09-27 15:56:25,902 ProcessRunner.java:78 - stargate6-0>  at [Source: (String)"{"malformed":"; line: 1, column: 14]
[NEXT LOG LINE, NOT STACK TRACE]
```

### CODE REVIEW

File: persistence-api/src/main/java/io/stargate/db/AuthenticatedUser.java [hunk 1]
```diff
@@ -16,7 +16,6 @@
 package io.stargate.db;
 
 import com.datastax.oss.driver.shaded.guava.common.collect.ImmutableMap;
-import com.datastax.oss.driver.shaded.guava.common.collect.ImmutableMap.Builder;
```
Comment (tatu-at-datastax) [inline persistence-api/src/main/java/io/stargate/db/AuthenticatedUser.java:19]: This was done due to ErrorProne warning wrt "too generic static imports" (same for similar changes later on).

**Review by dougwettlaufer — APPROVED** [review]

**Review by mpenick — APPROVED** [review]
