### PR TITLE
GraphQL: test nested collections and fixes

### LINKED ISSUE #226: Add integration tests for nested collections in GraphQL
As a follow up for #225, we should add integration tests for nested collection support in GraphQL.

### LINKED ISSUE #260: GraphQL: bigint CQL data type incorrectly parsed as BigInteger
CQL `bigint` should be represented in java as `long`, not as an arbitrary-precision integer.

### PR DESCRIPTION
**Pull request by jorgebay**
Adds integration test for nested collections.

Found and fixed 2 issues in the process:

- `DataTypeMapping` bug (introduced in #225)
- GraphQL bug for CQL bigint support (filed as #260)

Resolves #260, resolves #226 .

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ testing/src/test/java/io/stargate/it/http/GraphqlTest.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6330550&bid=20569838)

**Review by dougwettlaufer — APPROVED** [review]

File: graphqlapi/src/main/java/io/stargate/graphql/schema/CustomScalar.java [hunk 1]
```diff
@@ -78,14 +78,20 @@
...
-        return null;
+        if (e instanceof Integer) {
+          return ((Integer) e).longValue();
+        }
+        throw new NumberFormatException(
+            String.format(
+                "Expected string for bigint scalar, obtained %s", e.getClass().getName()));
       },
-      e -> e.toString()),
+      Object::toString),
```
Comment (olim7t) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/CustomScalar.java:94]: I think we can reuse `graphql.Scalars.GraphQLLong` instead of building our own custom type. It would work for CQL type `counter` as well.

`graphql.Scalars` also defines `GraphQLShort`, `GraphQLByte`, `GraphQLBigDecimal` and `GraphQLBigInteger`, that all map directly to their CQL counterparts.

Comment (jorgebay) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/CustomScalar.java:94]: oh good tip, TIL those java representations of custom scalars existed, I've filed #272 that can be implemented w/ #261 .

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ testing/src/test/java/io/stargate/it/http/GraphqlTest.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6330550&bid=20569838)
