### PR TITLE
Fixes #752 - NPE for bad column name in Where clause

### LINKED ISSUE #752: io.stargate.web.service.WhereParser#parseWhere throws NPE for bad column name
If a bad `where` is passed to the restapi then an NPE is thrown if the provided column name doesn't exist. Relevant code block

```java
Object val = value.asText();
Column.ColumnType columnType = tableData.column(fieldName).type(); // <-- This is the NPE
if (columnType != null) {
    Column.ColumnType valueType;
    if (op == FilterOp.$CONTAINS) {
    if (columnType.isCollection()) {
        valueType =
            columnType.isMap()
                ? columnType.parameters().get(1)
                : columnType.parameters().get(0);
    } else {
        throw new RuntimeException(
            String.format(
                "Field %s: operation %s is only supported for collection types",
                fieldName, rawOp));
    }
```

We need to check if the column exists BEFORE grabbing the type.

### PR DESCRIPTION
**Pull request by eribeiro**
Fixes invalid field name in RestApiv2's where clause.

### CODE REVIEW

File: testing/src/test/java/io/stargate/it/http/RestApiv2Test.java [hunk 1]
```diff
@@ -563,6 +563,35 @@ public void getRowsWithNotFound() throws IOException {
...
+        objectMapper.writeValueAsString(row),
+        HttpStatus.SC_CREATED);
+
+    String whereClause = "{\"invalid_field\":{\"$eq\":\"test\"}}";
+    String body =
+        RestUtils.get(
+            authToken,
+            String.format(
+                "%s:8082/v2/keyspaces/%s/%s?where=%s", host, keyspaceName, tableName, whereClause),
+            HttpStatus.SC_INTERNAL_SERVER_ERROR);
```
Comment (dimas-b) [inline testing/src/test/java/io/stargate/it/http/RestApiv2Test.java:587]: Specifying an invalid field name in query params looks like a user error to me... Do we want to report it as  `SC_INTERNAL_SERVER_ERROR`? :thinking:

Comment (eribeiro) [reply testing/src/test/java/io/stargate/it/http/RestApiv2Test.java:587]: You right. I am trying to figure out why it's coming as 500 instead of 400.

File: restapi/src/main/java/io/stargate/web/service/WhereParser.java [hunk 2]
```diff
@@ -126,7 +126,12 @@
             conditions.add(conditionToWhere(fieldName, op, true));
           } else {
             Object val = value.asText();
-            Column.ColumnType columnType = tableData.column(fieldName).type();
+            Column column = tableData.column(fieldName);
+            if (column == null) {
+              throw new RuntimeException(
```
Comment (dougwettlaufer) [inline restapi/src/main/java/io/stargate/web/service/WhereParser.java:131]: Might want to throw an IllegalArgument and then catch it above so we can return a 400.

File: testing/src/test/java/io/stargate/it/http/RestApiv2Test.java (hunk 1 above)
Comment (dougwettlaufer) [reply testing/src/test/java/io/stargate/it/http/RestApiv2Test.java:587]: Looks like you caught it down here. See my comment above about throwing something other than a RuntimeException so we can catch and return 400 rather than 500.

File: restapi/src/main/java/io/stargate/web/service/WhereParser.java (hunk 2 above)
Comment (eribeiro) [reply restapi/src/main/java/io/stargate/web/service/WhereParser.java:131]: Yes, I pinpointed and changed that. 🙂 Btw, there are some other RuntimeExceptions that could be casted to IllegalArgumentException in WhereParser#parseWhere. Wdyt?

File: restapi/src/main/java/io/stargate/web/service/WhereParser.java [hunk 3]
```diff
@@ -91,15 +92,20 @@
...
                 String.format(
                     "Value entry for field %s, operation %s must be an object "
                         + "with two fields 'key' and 'value'.",
                     fieldName, rawOp));
           }
-          Column.ColumnType mapType = tableData.column(fieldName).type();
+          Column column = tableData.column(fieldName);
+          if (column == null) {
+            throw new IllegalArgumentException(
+                String.format("Unknown column name '%s'.", fieldName));
```
Comment (dimas-b) [inline restapi/src/main/java/io/stargate/web/service/WhereParser.java:104]: `Unknown field name` like in other similar places?

**Review by dougwettlaufer — APPROVED** [review]

File: restapi/src/main/java/io/stargate/web/resources/RowResource.java [hunk 4]
```diff
@@ -647,7 +647,7 @@ private Predicate getOp(Filter.Operator operator) {
   private static Object filterToValue(Object val, String name, Table tableData) {
     Column column = tableData.column(name);
     if (column == null) {
-      throw new IllegalArgumentException(String.format("unknown field name '%s'", name));
+      throw new IllegalArgumentException(String.format("unknown field name '%s'.", name));
```
Comment (dimas-b) [inline restapi/src/main/java/io/stargate/web/resources/RowResource.java:650]: nit: in other places we have upper case first letter :shrug:

**Review by dimas-b — APPROVED** [review]
