### PR TITLE
When creating a table with restapi default clustering to asc

### LINKED ISSUE #764: REST API for v2 create table fails when there is no "clusteringExpression" provided as part of the "tableOptions"
Consider the following example without the `clusteringExpression` in it and it fails.

```
curl -s --location \
--request POST https://db-region.apps.astra.datastax.com/api/rest/v2/schemas/keyspaces/astra2/tables \
--header "X-Cassandra-Token: CHANGE_ME" \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data '{
  "name": "astra2",
  "ifNotExists": true,
  "columnDefinitions":[
    {"name":"pk1","typeDefinition":"int","static":false},
    {"name":"pk2","typeDefinition":"text","static":false},
    {"name":"ck1","typeDefinition":"double","static":false},
    {"name":"ck2","typeDefinition":"date","static":false},
    {"name":"c1","typeDefinition":"timeuuid","static":false}
  ],
  "primaryKey":
    {
      "partitionKey":["pk1","pk2"],
      "clusteringKey":["ck1","ck2"]
    },
    "tableOptions":{
      "defaultTimeToLive":0
    }
  }'
{"description":"Unable to create table options null","code":400}
```

whereas, if I specify the `clusteringExpression`, the command works successfully.

```
curl -s --location \
--request POST https://db-region.apps.astra.datastax.com/api/rest/v2/schemas/keyspaces/astra2/tables \
--header "X-Cassandra-Token: CHANGE_ME" \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data '{
  "name": "astra2",
  "ifNotExists": true,
  "columnDefinitions":[
    {"name":"pk1","typeDefinition":"int","static":false},
    {"name":"pk2","typeDefinition":"text","static":false},
    {"name":"ck1","typeDefinition":"double","static":false},
    {"name":"ck2","typeDefinition":"date","static":false},
    {"name":"c1","typeDefinition":"timeuuid","static":false}
  ],
  "primaryKey":
    {
      "partitionKey":["pk1","pk2"],
      "clusteringKey":["ck1","ck2"]
    },
    "tableOptions":{
      "defaultTimeToLive":0
      ,"clusteringExpression":[{"column":"ck1","order":"ASC"},{"column":"ck2","order":"DESC"}]
    }
  }'
{"name":"astra2"}
```

### PR DESCRIPTION
**Pull request by dougwettlaufer**
Fixes #764

### CODE REVIEW

**Review by ivansenic — APPROVED** [review]
Clean and nice..

File: testing/src/main/java/io/stargate/it/http/RestApiv2Test.java [hunk 1]
```diff
@@ -691,6 +691,38 @@ public void createTableWithNullOptions() throws IOException {
...
+    String body =
+        RestUtils.post(
+            authToken,
+            String.format("%s:8082/v2/schemas/keyspaces/%s/tables", host, keyspaceName),
+            objectMapper.writeValueAsString(tableAdd),
+            HttpStatus.SC_CREATED);
+
+    SuccessResponse successResponse =
+        objectMapper.readValue(body, new TypeReference<SuccessResponse>() {});
+    assertThat(successResponse.getSuccess()).isTrue();
```
Comment (tomekl007) [inline testing/src/main/java/io/stargate/it/http/RestApiv2Test.java:723]: I don't see how that test verifies if the clustering was created with `ASC` or `DESC`. Would it be possible to assert it here?

**Review by mpenick — APPROVED** [review]

File: testing/src/main/java/io/stargate/it/http/RestApiv2Test.java (hunk 1 above)
Comment (dougwettlaufer) [reply testing/src/main/java/io/stargate/it/http/RestApiv2Test.java:723]: It's not in the response but I can turn around and get the table just to be safe. The point of this test was that before the change this request would have failed.
