### PR TITLE
closes #2209: implement retriable bridge calls

### LINKED ISSUE #2209: REST API tests fail with `Abrupt GOAWAY closed sent stream`
When Stargate V2 Bridge is behind a Nginx proxy, seems that in one specific case, we are hitting the below exception on the client side:

* It happens as part of the `RestApiV2QSchemaKeyspacesIT#keyspacesGetAll` test
* We are fetching a fairly large amount of keyspaces, app. above 200
   * note that there is no max concurrency set in SchemaManager, so it seems we are going for 100 queries at the same time
* Nginx responds to all requests with `200` (see logs below)

Possible causes:
* Mix of the gRPC versions, however I doubt it as it seems that the request never reaches the bridge and the communcation failure is between client and nginx:
   * client side:  `1.49.0`
   * nginx: `1.49.0`
   * bridge: `1.45.1`
* gRPC client issue together with Nginx: https://github.com/grpc/grpc-java/issues/8310
* Some kind of a timeout or something simillar, but considering the logs, I doubt it everything goes very fast

*REST API stack trace*
```
ERROR [grpc-nio-worker-ELG-2-2] 2022-11-07 14:16:37,448 MutinyInfrastructure.java:160 - Mutiny had to drop the following exception: io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.quarkus.grpc.runtime.supports.IOThreadClientInterceptor$1$1.onClose(IOThreadClientInterceptor.java:72)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.quarkus.opentelemetry.runtime.tracing.grpc.GrpcTracingClientInterceptor$TracingClientCallListener.onClose(GrpcTracingClientInterceptor.java:89)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:752)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:688)
	at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:34)
	at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:693)
	at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:458)
	at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:221)
	at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:441)
	at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:278)
	at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:192)
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:200)
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:444)
	at io.grpc.netty.NettyClientHandler$7.visit(NettyClientHandler.java:851)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:978)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:209)
	at io.grpc.netty.NettyClientHandler.goingAway(NettyClientHandler.java:839)
	at io.grpc.netty.NettyClientHandler.access$200(NettyClientHandler.java:91)
	at io.grpc.netty.NettyClientHandler$2.onGoAwayReceived(NettyClientHandler.java:278)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.goAwayReceived(DefaultHttp2Connection.java:237)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.onGoAwayRead0(DefaultHttp2ConnectionDecoder.java:217)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onGoAwayRead(DefaultHttp2ConnectionDecoder.java:583)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onGoAwayRead(Http2InboundFrameLogger.java:119)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readGoAwayFrame(DefaultHttp2FrameReader.java:581)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:271)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

*Nginx logs*
```
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/ExecuteQuery HTTP/2.0" 200 44 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/ExecuteQuery HTTP/2.0" 200 4770 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 284 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 265 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/ExecuteQuery HTTP/2.0" 200 4697 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 287 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 257 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/ExecuteQuery HTTP/2.0" 200 975 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 387 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 284 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"
192.168.64.10 - - [07/Nov/2022:14:23:35 +0000] "POST /stargate.StargateBridge/DescribeKeyspace HTTP/2.0" 200 5 "-" "grpc-java-netty/1.49.0"

```

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Adds our own configuration of the retriable bridge calls. By default, retries are enabled and done only once in case response status code in `UNAVAILABLE`.

From now, bridge must be received from `StargateRequestInfo`, except when you know what are you doing :)

**Which issue(s) this PR fixes**:
* Fixes #2209.
* Makes #2047 as won't fix.
* Makes #2353 as won't fix.

**Checklist**
- [x] Tests with retries
- [x] Configuration documentation

### CODE REVIEW

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java [hunk 1]
```diff
@@ -29,4 +34,25 @@ public interface GrpcConfig {
...
+
+  /** @return Defines retry strategy for bridge calls when using {@link RetriableStargateBridge}. */
+  @Valid
+  @NotNull
+  Retries retries();
+
+  interface Retries {
+
+    /** @return If call retries are enabled. */
+    @WithDefault("true")
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java:46]: We could alternatively just use `maxAttempts = 0` to indicate disabled (I am ok with separate `enabled` too).

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java [hunk 2]
```diff
@@ -29,4 +34,25 @@ public interface GrpcConfig {
...
+    boolean enabled();
+
+    /** @return List of status codes to execute retries for. */
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java:49]: Maybe add a comment on why we include, by default, UNAVAILABLE? (so it's easy to see in a few months when looking at this code).

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import io.stargate.bridge.proto.StargateBridge;
+import java.lang.annotation.Retention;
+import java.lang.annotation.Target;
+import javax.inject.Qualifier;
+
+/** Qualifier for retriable {@link StargateBridge}. */
+@Qualifier
+@Retention(RUNTIME)
+@Target({METHOD, FIELD, PARAMETER, TYPE})
+public @interface Retriable {}
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java:34]: Would it make sense to use name like `RetriableQualifier` as name `Retriable` would usually imply interface for capability, instead of annotation?

**Review by tatu-at-datastax — APPROVED** [review]
Looks great -- added some optional suggestions, feel free to use or ignore.

If I understand this correctly, it should "just work" for REST API too, since it takes in `StargateRequestInfo requestInfo` and this PR will register appropriate retriable stargate bridge into it.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java (hunk 1 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/config/GrpcConfig.java:46]: I like explicit boolean and also a validation that max retries is positive (which I miss, so adding)

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java (hunk 3 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java:34]: I kept the java naming standards here, there is no `Qualifier` suffix in the `javax.enterprise.inject.Default` or `javax.enterprise.inject.Any`

Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java:34]: but I can move it to the dedicated package

File: apis/sgv2-quarkus-common/src/main/resources/application.yaml [hunk 4]
```diff
@@ -62,8 +62,6 @@ quarkus:
       bridge:
         host: localhost
         port: 8091
-        retry: true
-        max-hedged-attempts: 0
```
Comment (ivansenic) [inline apis/sgv2-quarkus-common/src/main/resources/application.yaml:66]: @tatu-at-datastax Can you help here, what do you think should I leave this or remove?

Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/main/resources/application.yaml:66]: Hmmh. I think it is not good to have multiple competing retries, so perhaps leave it as `retry: false` (to document we are not enabling retries at this level).
And then see what performance tests show.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java (hunk 3 above)
Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/Retriable.java]: No problem, I think package is fine.
