### PR TITLE
Revisit GraphQL naming conventions (fixes #118)

### LINKED ISSUE #118: Cassandra to Graphql Naming Resolution
Cassandra's table and column names support full UTF while graphql only supports

```
/^[_a-zA-Z][_a-zA-Z0-9]*$/.
```

The resolution should have the follow attributes:

Be deterministic with schema changes and schema refreshes

Keep production traffic intact on schema changes

Be clear to the user

A proposal is to:

1. Remove surrounding quotes2. Change all names to lower camel for field names, upper camel for table names3. Convert any characters out of graphql bounds to its hex encoded equivalent4. If it starts with a number, prefix it with an underscore

On conflicts:

The non-altered field name is preferred and the other field names are hidden*If there is no un-alterned field and there is a conflict, the last field is chosen alphabetically and the other fields are hidden

Additionally, tables or columns created through the graphql endpoint should carry out the action and return an error message along with the response informing the user of the limitation.

Examples:

🕷 => x1F577"123" => _123"Hello world! => helloWorld

### LINKED ISSUE #176: GraphQL mutations do not respect camelCase definitions
So, explorations with alterTableAdd() and alterTableDrop() using a column called either "publishYear" or "publish_year" show that "publishYear" is changed to "publishyear". Here are mutations to test:

```graphql
mutation createLibraryTables {
  books: createTable(
    keyspaceName:"library", 
    tableName:"books", 
    partitionKeys: [ # The keys required to access your data
      { name: "title", type: {basic: TEXT} }
    ]
    values: [ # The values associated with the keys
      { name: "author", type: {basic: TEXT} }
      { name: "genre", type: {basic: TEXT}}
    ] 
  )
}
# alter the books table to add another column "publishYear" of data type INT
mutation alterTableAddPUBLISHYEAR {
  alterTableAdd(
    keyspaceName:"library",
    tableName:"books",
    toAdd:[{
      name: "publishYear",
      type: {
        basic: INT
      }
    }
    ]
  )
}
# alter the books table to delete that column
mutation alterTableDropPUBLISHYEAR {
  alterTableDrop(
    keyspaceName:"library",
    tableName:"books",
    toDrop:[ "publishYear"]
  )
}
# alter the books table to add another column "publish_year" of data type INT
mutation alterTableAddPUBLISH_YEAR {
  alterTableAdd(
    keyspaceName:"library",
    tableName:"books",
    toAdd:[{
      name: "publish_year",
      type: {
        basic: INT
      }
    }
    ]
  )
}
mutation alterTableDropPUBLISH_YEAR {
  alterTableDrop(
    keyspaceName:"library",
    tableName:"books",
    toDrop:[ "publish_year"]
  )
}
```

### LINKED ISSUE #365: GraphQL schema processing error in CI (shouldSupportSingleMutationWithAtomicDirective)
```
Step #7 - "dse-6.8": INFO  [main] 2020-11-02 14:05:01,336 ExternalStorage.java:106 - About to run [engine:junit-jupiter]/[class:io.stargate.it.http.GraphqlTest]/[method:shouldSupportSingleMutationWithAtomicDirective()] with storage cluste
r version 6.8
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,388 StargateContainer.java:348 - sg0-0> ERROR [qtp1841489011-532] 2020-11-02 14:05:01,388 CustomGraphQLServlet.java:96 - Error initializing the GraphQL schema
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0> You have redefined the type 'BUdt' from being a 'GraphQLObjectType' to a 'GraphQLObjectType'
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLTypeCollectingVisitor.assertTypeUniqueness(GraphQLTypeCollectingVisitor.java:105)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLTypeCollectingVisitor.visitGraphQLObjectType(GraphQLTypeCollectingVisitor.java:38)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLObjectType.accept(GraphQLObjectType.java:199)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:72)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.util.Traverser.traverse(Traverser.java:144)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:59)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:51)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:38)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.SchemaUtil.allTypes(SchemaUtil.java:48)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:111)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:40)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:529)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:515)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at io.stargate.graphql.schema.DmlSchemaBuilder.build(DmlSchemaBuilder.java:141)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at io.stargate.graphql.schema.SchemaFactory.newDmlSchema(SchemaFactory.java:18)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet$RequestHandlerReference.computeHandler(CustomGraphQLServlet.java:344)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet$RequestHandlerReference.get(CustomGraphQLServlet.java:335)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet.handle(CustomGraphQLServlet.java:94)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at graphql.kickstart.servlet.CustomGraphQLServlet.doPost(CustomGraphQLServlet.java:77)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,389 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.Server.handle(Server.java:501)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,390 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
Step #7 - "dse-6.8": INFO  [Exec Stream Pumper] 2020-11-02 14:05:01,391 StargateContainer.java:348 - sg0-0>     at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by olim7t**
Name GraphQL types directly after tables. Only change them if there are
special characters, or they clash with our internal type names.

Fix case-sensitivity in generated CQL queries.

Fixes #118
Fixes #176
Fixes #365

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- graphqlapi/src/main/java/io/stargate/graphql/util/Naming.java  13
- graphqlapi/src/test/java/io/stargate/graphql/util/NamingTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6295678&bid=20479016)

**Comment by csplinter** [comment]
Have we considered implementing the suggestion in #125 ?

**Comment by jorgebay** [comment]
I think we can continue the discussion on the ticket.

**Comment by mpenick** [comment]
Are we going to keep the original `cqlName` state with the field operations? i.e. there's no need for a `String toCql(String gqlName)`?

**Comment by jorgebay** [comment]
I think naming strategy should be resilient to collisions in GraphQL, we should play nice with existing db schemas that want a GraphQL API on top.

Being deterministic on how those names are generated gives us a behaviour we can document (ie: UDTs first, then maps entries, followed by table types). We can advise against using `"foo_bar"` and `"FooBar"` in the same schema, and we can document how that conflict is going to be resolved.

If after a schema is generated in graphql, a user adds a new UDT which name collides with an existing object, its going to be resolved by the same rules, that the change might result in a breaking change for their graphql schema. This is not an issue we should optimize for.

We have to use the naming convention that feels natural for the user. We shouldn't design an API for the edge case, most users won't define their tables like `"foo_bar"` and `"FooBar"` in the same keyspace.

For example, mutation to insert in the table `books_by_author` should be `insertBooksByAuthor()`. In the same way, if the user defines `BooksByAuthor` as a table name, it should also be `insertBooksByAuthor()`

To put in another way, I think having a user-friendly API and a consistent naming convention that looks graphql-ish is more important than try to deliver inversible/bijective rule for our simplicity.

**Comment by olim7t** [comment]
Updated to reflect recent discussions. I still need to adapt the integration tests.

**Comment by olim7t** [comment]
I ended up not applying the inverse conversion in DDL mutations. This means table and column names appear exactly how they will be in the database. For example, the mutation:

```graphql
mutation {
  createTable(
    keyspaceName: "FooBar"
    tableName: "Hello"
    partitionKeys: [{ name: "World!", type: {basic: INT} }]
  )
}
```
Will generate the CQL query:
```
CREATE TABLE "FooBar"."Hello"("World!" int PRIMARY KEY)
```
But once translated back into GraphQL types, the column name will be escaped:
```graphql
type Hello {
  Worldx21_: Int
}
```

It feels more intuitive that way, because when we execute DDL mutations we're explicitly thinking in terms of table and columns, not GraphQL types and fields.

**Comment by dimas-b** [comment]
> partitionKeys: [{ name: "World!", type: {basic: INT} }]

Would it make sense to pre-check the names and deny schema operations that result in element names that cannot be represented in GraphQL? This would apply only to schema changes initiated from GraphQL, of course. WDYT?

**Comment by olim7t** [comment]
> Would it make sense to pre-check the names and deny schema operations that result in element names that cannot be represented in GraphQL (without adjustments)?

I'd rather avoid denying operations, especially if there's no hard technical reason to do so.

FWIW, this only applies to columns, I realized yesterday that table names are constrained to [a-zA-Z_0-9]+. So this is really an edge case.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 1]
```diff
@@ -0,0 +1,240 @@
...
+  }
+
+  private NameConversions() {}
+
+  public static String toGraphql(String cqlName, IdentifierType type) {
+    if (cqlName == null || cqlName.isEmpty()) {
+      throw new IllegalArgumentException("CQL name must be non-null and not empty");
+    }
+    if (type == IdentifierType.TABLE) {
+      for (Map.Entry<String, String> entry : RESERVED_GRAPHQL_NAMES.entrySet()) {
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:36]: Any reason not to use `RESERVED_GRAPHQL_NAMES.get(cqlName)` here?

Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:36]: No 😳 
I'll change it.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 2]
```diff
@@ -0,0 +1,240 @@
...
+    while (i < length) {
+      char c = source.charAt(i);
+      // Handle this case separately because it consumes two characters:
+      if (i < length - 1 && Character.isSurrogatePair(c, source.charAt(i + 1))) {
+        result = appendHex(result, source, i);
+        i += 2;
+      }
+      // Other cases where we escape: leading double underscores, leading digit, character not
+      // allowed in GraphQL, or 'x' followed by something that could be interpreted as a hex escape.
+      else if ((i == 0 && length > 1 && c == '_' && source.charAt(1) == '_')
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:80]: These first checks could be moved out of the loop. 

```java
if ((source.length() > 1 && source.startsWith("__")) || isDigit(source.charAt(0))) {
   result = appendHex(result, source, 0)
}
```

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 3]
```diff
@@ -0,0 +1,240 @@
...
+          || (i == 0 && isDigit(c))
+          || !isValidGraphql(c)
+          || (c == 'x' && lengthOfHexEscape(source, i) > 0)) {
+        result = appendHex(result, source, i);
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:84]: I'm wondering if it would be clearer/faster to do a pre-pass checking for invalid chars instead of interleaving the allocation logic.

```java
    boolean invalidPrefix = hasInvalidPrefix(source);

    if (invalidPrefix || requiresHexEscape(source)) {
      StringBuilder result = new StringBuilder();

      // ...

      return result.toString();
    } else {
      return source;
    }
```

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameMapping.java [hunk 4]
```diff
@@ -20,13 +20,18 @@
 import io.stargate.db.schema.Column;
 import io.stargate.db.schema.Table;
 import io.stargate.db.schema.UserDefinedType;
-import io.stargate.graphql.util.CaseUtil;
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameMapping.java:23]: `CaseUtil.java` and `util` util package can probably be removed.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 5]
```diff
@@ -0,0 +1,240 @@
...
+  }
+
+  private static String hexEscape(String source) {
+    StringBuilder result = null;
+    int length = source.length();
+    int i = 0;
+    while (i < length) {
+      char c = source.charAt(i);
+      // Handle this case separately because it consumes two characters:
+      if (i < length - 1 && Character.isSurrogatePair(c, source.charAt(i + 1))) {
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:74]: Might be simplified by iterating code points:

```java
      while (i < length) {
        int c = source.codePointAt(i);
        int charCount = Character.charCount(c);

        if (charCount > 1 || !isValidGraphql(c) || (c == 'x' && lengthOfHexEscape(source, index) > 0)) {
           // Hex escape
        } else {
          // ... 
        }
        i += charCount;
      }
```

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java (hunk 3 above)
Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:84]: Yeah my approach is a bit convoluted, the only advantage is that it traverses the string only once, but that's probably not significant enough to justify the complexity.
I'll do it as you suggest, thanks.

Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java]: Addressed in latest commit, it looks much cleaner now 👍

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 6]
```diff
@@ -0,0 +1,253 @@
...
+      graphqlName += "Udt";
+    }
+    return graphqlName;
+  }
+
+  public static String toCql(String graphqlName, IdentifierType type) {
+    if (graphqlName == null || graphqlName.isEmpty()) {
+      throw new IllegalArgumentException("GraphQL name must be non-null and not empty");
+    }
+    if (type == IdentifierType.UDT) {
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:58]: minor: From Codacy this could be: `if (type == IdentifierType.UDT && graphqlName.endsWith("Udt")) {`

**Review by mpenick — APPROVED** [review]
LGTM. (One minor, ignorable thing from the automated code review thing). The build failed because of timeouts unrelated to these changes. I've seen this on my branches too. I restarted your build in hopes that it completes successfully.

```
Step #7 - "dse-6.8": [ERROR]   CollectionTest.testUpgrade:202 ? SocketTimeout timeout
```

**Comment by olim7t** [comment]
The CI errors are caused by #365, looking into that.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java [hunk 7]
```diff
@@ -0,0 +1,251 @@
...
+          .put("Blob", "Blox62_")
+          .put("SmallInt", "SmallInx74_")
+          .put("TinyInt", "TinyInx74_")
+          .put("Timestamp", "Timestamx70_")
+          .put("Time", "Timx65_")
+          .build();
+
+  private static ImmutableMap<String, String> RESERVED_PREFIXES =
+      ImmutableMap.<String, String>builder()
+          .put("Entry", "Entrx79_")
```
Comment (jorgebay) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:240]: `"insert", "update", "delete"` should also be reserved.

**Review by jorgebay — COMMENTED** [review]
Left a remark below.

Also note that GraphQL [README](https://github.com/stargate/stargate/blob/master/graphqlapi/README.md) file needs to be updated as well.

**Comment by jorgebay** [comment]
Outside the code review, I wanted to share my concerns about the overall approach. While it might look that it doesn't limit to a naming convention, it's not committing to any naming convention.

Take for example a table named "users", the queries and mutations generated will be: `insertusers()`, `deleteusers()`, ... and the query `users()`, with no separation of words while the types will be `users`, `usersInput`, `usersInput`, `usersResult`, ... using camel case.

For a table named "user_activity" (snake case being a common convention in CQL/SQL), it will generate `insertuser_activity()` and `user_activity()`, mixing underscores with no separation. On the other hand, types will be named `user_activity`, `user_activityInput`, `user_activityResult` mixing snake case and camel case.

For case-sensitive CQL tables, like "Users", the types created look good but the queries and mutations mix conventions: `insertUsers()` and `Users()`. Also it's worth noting that case-sensitivity and double quotes in CQL identifiers is an obscure feature.

Additionally, for built-in types and queries we are using camel case convention which is the most common convention in GraphQL. For example, types like `MutationOptions`, `QueryConsistency`, ... and mutations like `createKeyspace()`, `createTable()`, etc.

I think not having a good end result in any of the naming conventions is a red flag for me. 

As an analogy, while in general users can code in Java or JavaScript using snake case, publishing a library in snake case in those languages is something I would like to avoid.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java (hunk 7 above)
Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:240]: I think we are good. We only use those prefixes is in the `Mutation` type and they are unconditionally prepended. If we have two tables named `foo` and `insertfoo`, the corresponding fields will be `insertfoo` and `insertinsertfoo`.

Comment (jorgebay) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:240]: Doesn't `insertfoo()` query (table `insertfoo`) collide with `insertfoo()` mutation (table `foo`)?

**Review by dougwettlaufer — APPROVED** [review]

**Comment by dougwettlaufer** [comment]
> Outside the code review, I wanted to share my concerns about the overall approach. While it might look that it doesn't limit to a naming convention, it's not committing to any naming convention.

I kind of like that aspect of it. If you're putting Stargate on top of an existing schema then it just works. Sure some of the graphql things might not look pretty but you don't have to do a major overhaul just because you want to run Stargate. Now if you're starting from scratch or in a position to go through and rename stuff then all of your graphql will look pretty but it's not a deal breaker. 


> For a table named "user_activity" (snake case being a common convention in CQL/SQL), it will generate insertuser_activity() and user_activity(), mixing underscores with no separation. On the other hand, types will be named user_activity, user_activityInput, user_activityResult mixing snake case and camel case.

Do you think maybe we should follow whatever type is presented by the table? For example table `user_activity` would result in `insert_user_activity()`while table `users` would still be `insertusers()`?

**Comment by olim7t** [comment]
> Do you think maybe we should follow whatever type is presented by the table? For example table `user_activity` would result in `insert_user_activity()`while table `users` would still be `insertusers()`?

I'm a bit wary about this, because It's going to be hard to come up with a reliable rule. Also someone might generate GraphQL queries dynamically, the more rules we have the more difficult it is to predict operation names.

But maybe we can insert the underscore when the table starts with a lower-case letter. That sounds reasonable and simple enough.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java (hunk 7 above)
Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:240]: No, queries and mutations belong to different types:
```
type Mutation {
  insertfoo
  insertinsertfoo
}
type Query {
  foo
  insertfoo
}
```

**Comment by olim7t** [comment]
Merged.

I kept mutation names as-is, as explained I think more rules will introduce more conflicts. We can create a follow-up ticket if we reconsider.

I created #396 to address the readme.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java (hunk 7 above)
Comment (jorgebay) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/NameConversions.java:240]: oh, nice!
