### PR TITLE
GraphQL: Surface conversion errors to the client (fixes #256)

### LINKED ISSUE #256: Improve error handling when building GraphQL schema
Error handling leaves a lot to be desired. For example, the code sometimes swallows exceptions:
```java
try {
  additionalTypes = buildTypesForTable(table);
  tableQueryField = buildQuery(table);
  tableMutationFields = buildMutations(table);
} catch (Exception e) {
  log.warn("Skipping table " + table.name());
  continue;
}
```
Also, end users will not always have access to the logs. We should find a way to surface something to them: not necessarily the exact error but at least that something went wrong for table X or column Y. I'm not sure what the best approach would be, maybe a special GraphQL query that would return a list of errors.

### PR DESCRIPTION
**Pull request by olim7t**
Expected or unexpected errors can happen when we convert the CQL data model into a GraphQL schema. Up to this point, those errors are logged on the server. The user who manages the data model won't necessarily have access to those logs.

The goal of this PR is to surface them in the GraphQL schema. The best way I've found is to add a special `__conversionWarnings` query. I also added a comment on this query with all the warnings, because it might be convenient to have them in `schema.graphql` without having to execute a query (and I think there won't be a lot of warnings in general).

Example scenarios that produce warnings:
* tuple columns (not implemented yet): `create table foo(k int primary key, t tuple<int,text>)`
* name clash between two tables: `create table foo_bar(k int primary key); create table "fooBar"(k int primary key)`
* name clash between two columns within the same table: `create table foo(k int primary key, a int, "A" text)`

How it looks in the schema definition:
```
type Query {
  [...]
  # Warnings encountered during the translation of the backend schema into GraphQL.
  # For convenience they are also listed below:
  # - Can't convert column foo.a because its GraphQL name a would collide with column A
  __conversionWarnings: [String]
}
```
How it looks as a query:
```
query {
  __conversionWarnings
}
```
Result:
```
{
  "data": {
    "__conversionWarnings": [
      "Can't convert column foo.a because its GraphQL name a would collide with column A"
    ]
  }
}
```

### CODE REVIEW

File: graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java [hunk 1]
```diff
@@ -304,16 +310,22 @@ private GraphQLFieldDefinition buildDelete(Table table) {
...
+        try {
+          fields.add(
+              GraphQLInputObjectField.newInputObjectField()
+                  .name(graphqlName)
+                  .type(fieldFilterInputTypes.get(column.type()))
+                  .build());
+        } catch (Exception e) {
+          warnings.add(
+              String.format(
+                  "Could not create filter input type for column %s.%s, skipping (%s)",
```
Comment (jorgebay) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java:324]: NIT: We could add a more clear notation for column+table: `"[...] for column %s in table %s [...]"`

File: graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java [hunk 2]
```diff
@@ -423,21 +443,44 @@ public GraphQLObjectType buildType(Table table) {
...
 
-  private GraphQLFieldDefinition.Builder buildOutputField(Table table, Column columnMetadata) {
-    return new GraphQLFieldDefinition.Builder()
-        .name(nameMapping.getGraphqlName(table, columnMetadata))
-        .type(fieldOutputTypes.get(columnMetadata.type()));
+  private GraphQLFieldDefinition buildWarnings() {
+    StringBuilder description =
+        new StringBuilder(
+            "Warnings encountered during the translation of the backend schema into GraphQL.\n"
+                + "For convenience they are also listed below:");
```
Comment (jorgebay) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java:470]: NIT: Can we change the message when there aren't any issues to avoid scaring the user, something like "No issues found when generating the GraphQL schema."

**Review by jorgebay — APPROVED** [review]
I think its a super convenient solution from the user pov 👍  

Minor nits below.

File: graphqlapi/src/main/java/io/stargate/graphql/schema/FieldInputTypeCache.java [hunk 3]
```diff
@@ -50,18 +50,31 @@ protected GraphQLInputType compute(Column.ColumnType columnType) {
   }
 
   private GraphQLInputType computeUdt(UserDefinedType udt) {
+    String graphqlName = nameMapping.getGraphqlName(udt);
+    if (graphqlName == null) {
+      throw new IllegalArgumentException(
+          String.format(
+              "Could find a GraphQL name mapping for UDT %s, "
```
Comment (dougwettlaufer) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/FieldInputTypeCache.java:57]:
```suggestion
              "Could not find a GraphQL name mapping for UDT %s, "
```

File: graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java [hunk 4]
```diff
@@ -369,27 +381,35 @@ private GraphQLType buildQueryOptionsInputType() {
...
-    for (Column columnMetadata : table.columns()) {
-      try {
-        GraphQLInputObjectField field =
-            GraphQLInputObjectField.newInputObjectField()
-                .name(nameMapping.getGraphqlName(table, columnMetadata))
-                .type(fieldInputTypes.get(columnMetadata.type()))
-                .build();
-        input.field(field);
-      } catch (Exception e) {
-        log.error(
```
Comment (dougwettlaufer) [inline graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java:391]: We don't at least want a warn on the server side too?

**Review by dougwettlaufer — APPROVED** [review]

File: graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java (hunk 4 above)
Comment (olim7t) [reply graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java:391]: Right, I'll add them back.

I think error logs should target operators, so I'm always wary about logging too much: for example if the CQL data model causes a a name clash in `NameMapping`, it's a user issue, not something an operator should be paged about.
But the catch blocks in this class cover unexpected errors, so it's reasonable to log at WARN level.
