### PR TITLE
Fixes #2674: support microsecond fractions for ISO-8601 date/time for REST API

### LINKED ISSUE #2674: REST Timestamp with additional fraction not accepted
In the In-coordiator (DropWizard based) REST API, the timestamp of below format is accepted and the same fails in the Quarkus based REST API
```timestamp
2023-07-13T14:02:06.018850Z
```
**Steps to reproduce:**
1. Create table with a timestamp column

`/v2/schemas/keyspaces/testks1/tables`

```json
{
    "name": "employee1",
    "ifNotExists": false,
    "columnDefinitions": [
        {
            "name": "id",
            "typeDefinition": "int"
        },
        {
            "name": "name",
            "typeDefinition": "text"
        },
        {
            "name": "createdAt",
            "typeDefinition": "timestamp"
        }
    ],
    "primaryKey": {
        "partitionKey": [
            "id"
        ]
    },
    "tableOptions": {
        "defaultTimeToLive": 0
    }
}
```

2. Insert a record

`/v2/keyspaces/testks1/employee1`

```json
{
    "id": 123,
    "name": "emp2",
    "createdAt": "2023-07-13T14:02:06.018850Z"
}
```

In DropWizard REST API, it is working without any error and while getting back the row, we could see the last three 3 digits got truncated and returned as below

`/v2/keyspaces/testks1/employee1/123`

```json
{
    "count": 1,
    "data": [
        {
            "name": "emp2",
            "createdAt": "2023-07-13T14:02:06.018Z",
            "id": 123
        }
    ]
}
```
In Quarkus based REST API, the request to insert fails with below error
```json
{
    "description": "Invalid path for row to create, problem: Failed to deserialize field 'employee1.createdAt', problem: Text '2023-07-13T14:02:06.018850Z' could not be parsed, unparsed text found at index 23",
    "code": 400,
    "grpcStatus": null,
    "internalTxId": null
}
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes handling of date/time fields to allow second fraction for microseconds (up to 6 digits) instead of just millis (3); similar to what SGv1/REST supported.

**Which issue(s) this PR fixes**:
Fixes #2674

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: apis/sgv2-restapi/src/test/java/io/stargate/sgv2/it/RestApiV2QRowGetIT.java [hunk 1]
```diff
@@ -847,7 +847,9 @@ public void getRowsWithTimestampQuery() {
             map("id", 3, "firstName", "Graham", "created", "2021-04-22T18:42:22.139-0800"),
             map("id", 4, "firstName", "Joel", "created", "2021-04-22T18:42:22.139+07"),
             map("id", 4, "firstName", "Deborah", "created", "2021-04-22T18:42:22.139-05"),
-            map("id", 5, "firstName", "Timothy", "created", timestampAsMsecs)));
+            map("id", 5, "firstName", "Timothy", "created", timestampAsMsecs),
+            // 13-Jul-2023, tatu: [stargaate#2674] Support microsecond fractions too
+            map("id", 6, "firstName", "Jerome", "created", "2023-07-13T14:02:06.018850Z")));
```
Comment (kathirsvn) [inline apis/sgv2-restapi/src/test/java/io/stargate/sgv2/it/RestApiV2QRowGetIT.java:852]: Can we also read this back and check if it's retaining only up to milliseconds precision and dropping the microseconds part?
Also, do we need to document this somewhere that the microseconds fraction will be allowed but dropped?

Comment (tatu-at-datastax) [reply apis/sgv2-restapi/src/test/java/io/stargate/sgv2/it/RestApiV2QRowGetIT.java:852]: Dropping of value is verified by the unit test (`ToProtoConverterTest.java`) -- value compared to has only milliseconds.

Documentation is a good question, need to work with @johnsmartco on how to do that (in context where date/time values, allowed are discussed). I think it is related to Cassandra only storing millisecond timestamp.

**Review by kathirsvn — APPROVED** [review]
