### PR TITLE
Fix Values.byteBuffer to return non-empty buffer (fixes #1676)

### LINKED ISSUE #1676: Values.byteBuffer returns an empty buffer
In [Values](https://github.com/stargate/stargate/blob/master/grpc-proto/src/main/java/io/stargate/grpc/Values.java#L232-L238):
```java
  public static ByteBuffer byteBuffer(Value value) {
    checkInnerCase(value, InnerCase.BYTES);

    ByteBuffer bytes = ByteBuffer.allocate(value.getBytes().size());
    value.getBytes().copyTo(bytes);
    return bytes;
  }
```

This does not reset the position after copying, resulting in an empty buffer.

Fix:

```java
  public static ByteBuffer byteBuffer(Value value) {
    checkInnerCase(value, InnerCase.BYTES);

    return value.getBytes().asReadOnlyByteBuffer();
  }
```

### PR DESCRIPTION
**Pull request by olim7t**
**Which issue(s) this PR fixes**:
Fixes #1676

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: grpc-proto/src/main/java/io/stargate/grpc/Values.java [hunk 1]
```diff
@@ -232,9 +236,7 @@ public static double double_(Value value) {
   public static ByteBuffer byteBuffer(Value value) {
     checkInnerCase(value, InnerCase.BYTES);
 
-    ByteBuffer bytes = ByteBuffer.allocate(value.getBytes().size());
-    value.getBytes().copyTo(bytes);
-    return bytes;
+    return value.getBytes().asReadOnlyByteBuffer();
```
Comment (tatu-at-datastax) [inline grpc-proto/src/main/java/io/stargate/grpc/Values.java:239]: Makes sense, as per issue description. Would benefit from Javadoc stating it too since call sequence does not immediately suggest (at least to me) the behavior.

**Review by tatu-at-datastax — APPROVED** [review]
