### PR TITLE
closes #2389: fix retriable stargate bridge being exposed as service

### LINKED ISSUE #2389: Quarkus starts gRPC server in APIs `v2.0.6`
```
WARN  [main] 2023-01-19 13:01:26,286 GrpcServerRecorder.java:108 - Using legacy gRPC support, with separate new HTTP server instance. Switch to single HTTP server instance usage with quarkus.grpc.server.use-separate-server=false property
INFO  [vert.x-eventloop-thread-1] 2023-01-19 13:01:26,417 GrpcServerRecorder.java:223 - gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
INFO  [main] 2023-01-19 13:01:26,445 Channels.java:216 - Creating Netty gRPC channel ...
```

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Fixes starting of the gRPC service. In fact the `RetriableStargateBridge` was exposed as a gRPC service. I will write some additional details in the code.

I am not sure if this should be considered as security risk and vulnerability in versions `2.0.6` and `2.0.7`. Having access to that exposed port, would enable one to gain schema information over the bridge. Any other op requires valid auth token, so no issues there. 

**Which issue(s) this PR fixes**:
Fixes #2389

### CODE REVIEW

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/RetriableStargateBridge.java [hunk 1]
```diff
@@ -18,33 +18,23 @@
...
-import io.stargate.sgv2.api.common.grpc.qualifier.Retriable;
-import javax.inject.Inject;
-import javax.inject.Singleton;
 
 /**
  * An implementation of the {@link StargateBridge} that executes retries based on the
  * GrpcConfig.Retries configuration.
  */
-@Singleton
-@GrpcService
```
Comment (ivansenic) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/RetriableStargateBridge.java:37]: This is the wrong annotation, that was exposing this as a service. However, I was confused by the following build time error that made me add it:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final:build (default) on project sgv2-docsapi: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: A gRPC service bean must be annotated with @io.quarkus.grpc.GrpcService: CLASS bean [types=[io.stargate.sgv2.api.common.grpc.RetriableStargateBridge, io.stargate.bridge.proto.StargateBridge, io.quarkus.grpc.MutinyService, java.lang.Object], qualifiers=[@Retriable, @Any], target=io.stargate.sgv2.api.common.grpc.RetriableStargateBridge]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:161)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:559)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.IllegalStateException: A gRPC service bean must be annotated with @io.quarkus.grpc.GrpcService: CLASS bean [types=[io.stargate.sgv2.api.common.grpc.RetriableStargateBridge, io.stargate.bridge.proto.StargateBridge, io.quarkus.grpc.MutinyService, java.lang.Object], qualifiers=[@Retriable, @Any], target=io.stargate.sgv2.api.common.grpc.RetriableStargateBridge]
[ERROR] 	at io.quarkus.grpc.deployment.GrpcServerProcessor.validateBindableService(GrpcServerProcessor.java:477)
[ERROR] 	at io.quarkus.grpc.deployment.GrpcServerProcessor.validateBindableServices(GrpcServerProcessor.java:465)
[ERROR] 	... 11 more
[ERROR] -> [Help 1]
[ERROR] 

```

**Comment by tatu-at-datastax** [comment]
Interesting. Great that this was caught now.

I think that since this is not exposed via Astra, it's not a security hole for us and not a blocker.
But would still be good to get in for our deployment if timing allows.

**Review by tatu-at-datastax — APPROVED** [review]
