### PR TITLE
closes #2031: dead leaves to accept custom metadata

### LINKED ISSUE #2031: Delete dead leaves should manually set the bridge metadata
The Docs V2 depends on the request context to be present, in order to call the bridge.. However, in case of the dead leaves, the deletion is actually done asynchronously, outside of the request.. Thus, we need to manually setup the metadata for the dead leaf call..

```
2022-08-15 16:27:25,831 WARN  [io.sta.sgv.doc.ser.que.ReadDocumentsService] (executor-thread-0) Unable to delete dead leaves.: java.lang.IllegalStateException: No RESTEasy Reactive request in progress
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getContext(ContextProducers.java:138)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.securityContext(ContextProducers.java:132)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.create(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.arc$delegate(Unknown Source)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.getUserPrincipal(Unknown Source)
	at io.stargate.sgv2.api.common.token.impl.PrincipalTokenResolver.resolve(PrincipalTokenResolver.java:32)
	at io.stargate.sgv2.api.common.token.CassandraTokenConfiguration_ProducerMethod_principalTokenResolver_ae89453fb31e735e995a48596d0fde3310ffe69f_ClientProxy.resolve(Unknown Source)
	at io.stargate.sgv2.api.common.StargateRequestInfo.<init>(StargateRequestInfo.java:55)
	at io.stargate.sgv2.api.common.StargateRequestInfo_Bean.create(Unknown Source)
	at io.stargate.sgv2.api.common.StargateRequestInfo_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
	at io.stargate.sgv2.api.common.StargateRequestInfo_ClientProxy.arc$delegate(Unknown Source)
	at io.stargate.sgv2.api.common.StargateRequestInfo_ClientProxy.getStargateBridge(Unknown Source)
	at io.stargate.sgv2.docsapi.service.write.WriteBridgeService.lambda$deleteDeadLeaves$13(WriteBridgeService.java:458)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:29)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Fixes bug described in the #2031.. 

Now this is the quick fix, but introduces a bit of a mixed design now. Should `StargateBridge` be retrieved always from the `StargateRequestInfo` or not? I guess long term we need to have a single approach.. However, it requires some additional work mainly to fix all the tests.. So I am going to create a ticket for it: https://github.com/stargate/stargate/issues/2047

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated

### CODE REVIEW

File: apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/service/write/WriteBridgeService.java [hunk 1]
```diff
@@ -508,11 +502,16 @@ public Uni<ResultSet> deleteDeadLeaves(
...
-                executeBatch(
-                    requestInfo.getStargateBridge(),
-                    boundQueries,
-                    context.nested("ASYNC DOCUMENT CORRECTION")));
+            boundQueries -> {
+              if (metadata.keys().isEmpty()) {
+                return executeBatch(
+                    bridge, boundQueries, context.nested("ASYNC DOCUMENT CORRECTION"));
+              } else {
+                StargateBridge bridgeWithMetadata = GrpcClientUtils.attachHeaders(bridge, metadata);
```
Comment (EricBorczuk) [inline apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/service/write/WriteBridgeService.java:510]: :+1:

**Review by EricBorczuk — APPROVED** [review]
