### PR TITLE
Wait until the driver sees all nodes in tests (fixes #232)

### LINKED ISSUE #232: Fix flaky test MultipleStargateInstancesTest.shouldDistributeTrafficUniformly
The test `shouldDistributeTrafficUniformly` is failing often on CI.

Example:

```
Error:  Failures: 
Error:    MultipleStargateInstancesTest.shouldDistributeTrafficUniformly:117 
Expected size:<3> but was:<1> in:
<[Node(endPoint=/127.0.0.13:9043, hostId=a2e98542-13bd-4108-97b9-436fa05bf358, hashCode=7cba991a)]>
[INFO] 
Error:  Tests run: 195, Failures: 1, Errors: 0, Skipped: 3
```

### PR DESCRIPTION
**Pull request by olim7t**
Depends on #267.

### CODE REVIEW

File: testing/src/test/java/io/stargate/it/MultipleStargateInstancesTest.java [hunk 1]
```diff
@@ -57,26 +59,28 @@ public MultipleStargateInstancesTest(ClusterConnectionInfo backend) {
...
+        Collections.singletonList(DefaultNodeMetric.CQL_MESSAGES.getPath()));
+
+    CqlSessionBuilder cqlSessionBuilder =
+        CqlSession.builder().withConfigLoader(DriverConfigLoader.fromMap(config));
     for (String host : getStargateHosts()) {
       cqlSessionBuilder.addContactPoint(new InetSocketAddress(host, 9043));
     }
     session = cqlSessionBuilder.build();
+    await()
+        .atMost(Duration.ofMinutes(3))
```
Comment (dimas-b) [inline testing/src/test/java/io/stargate/it/MultipleStargateInstancesTest.java:82]: I'd go with a pessimistic timeout, something like 10 min, perhaps? Increasing the timeout will not actually increase the run time of successful (expected) runs, but will reduce spurious failures as we know CI is very slow.

Comment (dimas-b) [reply testing/src/test/java/io/stargate/it/MultipleStargateInstancesTest.java:82]: I think this timeout actually happened in the first CI run on this PR :thinking:

**Review by dimas-b — APPROVED** [review]

File: testing/src/test/java/io/stargate/it/MultipleStargateInstancesTest.java (hunk 1 above)
Comment (olim7t) [reply testing/src/test/java/io/stargate/it/MultipleStargateInstancesTest.java]: Yes, didn't see your comment but it was reached and I did increase it to 10 minutes.
Also added logs to check whether `system.peers` is not updated or the driver didn't get a gossip event.

**Review by dougwettlaufer — APPROVED** [review]

**Review by mpenick — APPROVED** [review]

**Review by mpenick — APPROVED** [review]
