### PR TITLE
Fix #1639: refactor Materialized View REST API ITs into separate test class

### LINKED ISSUE #1639: Refactor Rest API Integration tests that test Materialized Views into separate class
Since some persistence backends do not have support for Materialized Views, tests that exercise them will fail on such backends.
Currently we have at least one test in `RestApiv2RowsTest` (method `getAllRowsFromMaterializedView()`).
It would make sense to create a separate IT class to make it easier to exclude running of this test specifically for relevant backends.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Further refactors REST API v2 tests to move:

* Materialized View related tests into new class

The reason being that further testing by downstream projects has issues with a backend that does not (yet?) support Materialized Views, and test exclusion is easier with more granular division of tests methods into classes.

**Which issue(s) this PR fixes**:
Fixes #1639

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+import java.util.List;
+import java.util.Map;
+import java.util.Optional;
+import java.util.stream.Collectors;
+import org.apache.http.HttpStatus;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.TestInfo;
+
+/** Intermediate IT base class for use by REST API integration tests. */
+abstract class RestApiTestBase extends BaseIntegrationTest {
```
Comment (jeffreyscarpenter) [inline testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java:29]: Just FYI, this name may create some confusion upon merging into the v2.0.0 package, where a `io.stargate.it.http.BaseRestApiTest` has been added already.

Comment (tatu-at-datastax) [reply testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java:29]: Ohhh. Thanks, I'll change that then!

Comment (tatu-at-datastax) [reply testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java:29]: Ok I think I'll get this merged for `master`, merge & refactor in v2.0.0 to combine classes.

**Review by jeffreyscarpenter — APPROVED** [review]

File: testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java (hunk 1 above)
Comment (ivansenic) [reply testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java:29]: I would say this functionality already exists, check this peace of code :arrow_down:  https://github.com/stargate/stargate/blob/d0d0ddf15f05c9185d3e0b6ac9a0d3df4cb32ae7/testing/src/main/java/io/stargate/it/http/docsapi/CollectionsResourceIntTest.java#L83-L94

So `@CqlSessionSpec` and `@TestKeyspace CqlIdentifier keyspace` do the trick.. I like this annotation approach way more..

Comment (ivansenic) [reply testing/src/main/java/io/stargate/it/http/restapi/RestApiTestBase.java:29]: And I am not convinced create table and insert rows should be done is such a way.. The `CqlSessionSpec` has `initQueries` properties that can create table easily or add data transparently for the test setup..

**Review by ivansenic — APPROVED** [review]
Left a comment..
