### PR TITLE
Fix and test GraphQL error handling

### LINKED ISSUE #207: GraphQL: Improve error messages
The error messages for the GraphQL API do not give enough context to the user to be able to troubleshoot or figure out what they should fix. We should enumerate common error cases and ensure that we have thorough error messages for them.

For example, if you run a mutation that is not supported:
```
mutation {
  createKeyspace(
    name:"library", 
    dcs: { name:"dc1", replicas: 1 } 
  )
}
```

The only response is
```
{
  "data": null
}
```

TODO: fill in more examples

### PR DESCRIPTION
**Pull request by jorgebay**
Fixes #207 .

GraphQL over HTTP [surfaces errors](https://spec.graphql.org/June2018/#sec-Errors) in the property `"errors"`. This patch adds a small fix and tests for expected behaviour on graphql errors.

Also, I've unified the junit version used across all modules because it was giving me issues when running parameterized tests from IDE.

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- testing/src/test/java/io/stargate/it/http/GraphqlTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6312685&bid=20525161)

File: graphqlapi/src/main/java/io/stargate/graphql/graphqlservlet/CassandraUnboxingGraphqlErrorHandler.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import java.util.List;
 
 public class CassandraUnboxingGraphqlErrorHandler implements GraphQLErrorHandler {
```
Comment (mpenick) [inline graphqlapi/src/main/java/io/stargate/graphql/graphqlservlet/CassandraUnboxingGraphqlErrorHandler.java:25]: I know this is an existing name, but "unboxing" is a confusing name because it's more "processing" the errors or "converting" them. What about changing this to `CassandraGraphqlErrorHandler` and changing "unbox" to "convert" or "process".

Comment (jorgebay) [reply graphqlapi/src/main/java/io/stargate/graphql/graphqlservlet/CassandraUnboxingGraphqlErrorHandler.java:25]: Makes sense to give it another name, how `StargateGraphqlErrorHandler` sounds?

Comment (jorgebay) [reply graphqlapi/src/main/java/io/stargate/graphql/graphqlservlet/CassandraUnboxingGraphqlErrorHandler.java]: I've changed it to `StargateGraphqlErrorHandler`, lmkwyt

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- testing/src/test/java/io/stargate/it/http/GraphqlTest.java  4
- graphqlapi/src/main/java/io/stargate/graphql/graphqlservlet/StargateGraphqlErrorHandler.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6312685&bid=20525161)

**Review by mpenick — APPROVED** [review]
Nice tests!
