### PR TITLE
closes #2175: apis to report source api in the grpc metadata

### LINKED ISSUE #2175: API V2 bridge communication has wrong Source API
Getting this when trying to use the REST API V2, without cql scoped token:

```
{
  "description": "Unauthorized gRPC operation (Status.Code.PERMISSION_DENIED->401): PERMISSION_DENIED: Missing correct permission on stargate.rest_example_products: Not authorized to access stargate.rest_example_products for CREATE (from source api: cql)",
  "code": 401,
  "grpcStatus": "PERMISSION_DENIED",
  "internalTxId": null
}
```

It's either that:

* REST API does not define a source API in the default parameters
* Not using the default parameters
* Or bridge does not consider the passed source API for the auth

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
* adds source api as the metadata when communicating to the bridge
* adds bridge handling to read those values
* updates query handlers to support this for:
   * DSE 
   * C* 4
   * C* 3.11

**Which issue(s) this PR fixes**:
Fixes #2175.

**Checklist**
- [x] Bridge changes
- [x] Query handler changes

### CODE REVIEW

File: apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import javax.enterprise.context.ApplicationScoped;
+import javax.ws.rs.Produces;
+
+@ApplicationScoped
+public class SourceApiConfiguration {
+
+  @Produces
+  @SourceApi
+  public String sourceApi() {
+    return "rest";
```
Comment (tatu-at-datastax) [inline apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java:30]: Probably should be "docs"?

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java [hunk 2]
```diff
@@ -19,15 +19,35 @@ public class GrpcMetadataResolver {
   /** Metadata key for passing the cassandra token to the Bridge. */
   private final Metadata.Key<String> cassandraTokenKey;
 
+  /** Default metadata. */
+  private final Metadata defaultMetadata;
+
+  // TODO add validation @Pattern(regexp = "rest|graphql")  after
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:25]: We probably either want to just validate legal characters, or make set of acceptable ids configurable, to allow addition of new APIs by other developers?
If it was configurable we could add our own regex for production deployment to ensure no unknown ids were to be used.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java [hunk 3]
```diff
@@ -19,15 +19,35 @@ public class GrpcMetadataResolver {
...
   @Inject
-  public GrpcMetadataResolver(GrpcMetadataConfig config) {
+  public GrpcMetadataResolver(GrpcMetadataConfig config, @SourceApi String sourceApi) {
     this.tenantIdKey = Metadata.Key.of(config.tenantIdKey(), Metadata.ASCII_STRING_MARSHALLER);
     this.cassandraTokenKey =
         Metadata.Key.of(config.cassandraTokenKey(), Metadata.ASCII_STRING_MARSHALLER);
+
+    // default metadata includes source api
+    Metadata.Key<String> sourceApiKey =
+        Metadata.Key.of(config.sourceApiKey(), Metadata.ASCII_STRING_MARSHALLER);
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:35]: I know short-living garbage is not a big problem in general but couldn't we just create this key once (add a convenience method in `GrpcMetadataConfig` to get pre-created `Metadata.Key` instead of `String` for creating one) and reuse it? `Metadata.Key` is annotated as Immutable and hence thread-safe.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/StargateBridgeInterceptor.java [hunk 4]
```diff
@@ -35,18 +35,22 @@ public class StargateBridgeInterceptor implements ClientInterceptor {
...
+    Metadata metadata = metadataResolver.getDefaultMetadata();
+
     // StargateRequestInfo is request scoped bean
     // there is no better way to know if if's available
     // as we can intercept outside request
     // thus ensure context is active and has instances
     InjectableContext.ContextState contextState =
         Arc.container().requestContext().getStateIfActive();
-    if (null == contextState || !hasStargateRequestBean(contextState.getContextualInstances())) {
-      return next.newCall(method, callOptions);
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/StargateBridgeInterceptor.java:45]: So this call would not pass default metadata (for now mostly SourceApi) so need to change to pass it?

File: apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+import javax.ws.rs.Produces;
+
+/** Test config for the source api, so common can boot itself. */
+@ApplicationScoped
+public class SourceApiTestConfiguration {
+
+  @Produces
+  @SourceApi
+  public String sourceApi() {
+    return "rest";
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java:31]: For tests could perhaps use a distinct value, separate from values we use in prod?
Unless we have validation settings that prevent use of id like "test" in which case never mind.

File: auth-table-based-service/src/test/java/io/stargate/auth/SourceAPITest.java [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+            Map<String, ByteBuffer> map = new HashMap<>();
+            SourceAPI.GRAPHQL.toCustomPayload(map);
+
+            SourceAPI result = SourceAPI.fromCustomPayload(map, SourceAPI.CQL);
+
+            assertThat(result).isEqualTo(SourceAPI.GRAPHQL);
+        }
+
+        @Test
+        public void emptyMap() {
```
Comment (tatu-at-datastax) [inline auth-table-based-service/src/test/java/io/stargate/auth/SourceAPITest.java]: I know it's implicit but maybe add a comment stating this verifies that our default SourceAPI is CQL?

File: authnz/src/test/java/io/stargate/auth/SourceAPITest.java [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+      Map<String, ByteBuffer> map = new HashMap<>();
+      SourceAPI.GRAPHQL.toCustomPayload(map);
+
+      SourceAPI result = SourceAPI.fromCustomPayload(map, SourceAPI.CQL);
+
+      assertThat(result).isEqualTo(SourceAPI.GRAPHQL);
+    }
+
+    @Test
+    public void emptyMap() {
```
Comment (tatu-at-datastax) [inline authnz/src/test/java/io/stargate/auth/SourceAPITest.java:62]: I know it's implicit here, but maybe add a comment that this verifies that the default `SourceAPI` value, if nothing explicitly passed, is CQL?

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+import static java.lang.annotation.RetentionPolicy.RUNTIME;
+
+import java.lang.annotation.Documented;
+import java.lang.annotation.Retention;
+import javax.inject.Qualifier;
+
+@Documented
+@Retention(RUNTIME)
+@Qualifier
+public @interface SourceApi {}
```
Comment (tatu-at-datastax) [inline apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java:29]: Not sure what to do about this (if anything), but having 2 different `SourceApi`s (one enum in auth, for valid values for our auth; another this tag interface for config) is bit confusing.
Maybe this annotation could be `SourceApiDefinition` or something?

File: authnz/src/main/java/io/stargate/auth/SourceAPI.java [hunk 9]
```diff
@@ -17,11 +17,19 @@
...
 package io.stargate.auth;
 
+import java.nio.ByteBuffer;
+import java.nio.charset.StandardCharsets;
+import java.util.Arrays;
+import java.util.Map;
+import java.util.Objects;
+import java.util.Optional;
+
 public enum SourceAPI {
```
Comment (tatu-at-datastax) [inline authnz/src/main/java/io/stargate/auth/SourceAPI.java:27]: I know it didn't exist before, but Javadoc here would be nice; could mention that value is passed along as custom metadata (for CQL) or headers (bridge/grpc).

File: authnz/src/main/java/io/stargate/auth/SourceAPI.java [hunk 10]
```diff
@@ -31,4 +39,27 @@ public enum SourceAPI {
...
+
+  public static SourceAPI fromCustomPayload(Map<String, ByteBuffer> customPayload, SourceAPI defaultIfMissing) {
+    if (null == customPayload) {
+      return defaultIfMissing;
+    }
+
+    return Optional.ofNullable(customPayload.get(CUSTOM_PAYLOAD_KEY))
+            .flatMap(buffer -> {
+              String decode = StandardCharsets.UTF_8.decode(buffer).toString();
+              return Arrays.stream(SourceAPI.values()).filter(s -> Objects.equals(s.getName(), decode)).findFirst();
```
Comment (tatu-at-datastax) [inline authnz/src/main/java/io/stargate/auth/SourceAPI.java]: Why not just use `SourceAPI.valueOf(decode)`? To avoid exception for mismatching name?

File: testing/src/main/java/io/stargate/it/bridge/BridgeIntegrationTest.java [hunk 11]
```diff
@@ -137,4 +145,14 @@ protected QueryOuterClass.QueryParameters.Builder queryParameters(
   protected QueryOuterClass.QueryParameters.Builder queryParameters(CqlIdentifier keyspace) {
     return queryParameters(keyspace, false);
   }
+
+  protected static String sourceApi() {
```
Comment (tatu-at-datastax) [inline testing/src/main/java/io/stargate/it/bridge/BridgeIntegrationTest.java:149]: Since these are static and not meant for overridability, could just inline `sourceApi` value and interceptor closure.

File: apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java (hunk 1 above)
Comment (tatu-at-datastax) [inline apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java:30]: Looks like "rest" is used here because `AuthApi` has no enum for docs-api.
Might want to add a comment mentioning this since I first thought this was unintentional.

Comment (ivansenic) [reply apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java:30]: We don't have docs as the source API.. Historically, for the auth the docs and rest were grouped into `rest`.. 

There is a ticket for this, but this requires authz service implementations to respect the docs as the new source api: https://github.com/stargate/stargate/issues/1786

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java (hunk 2 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:25]: Does not make sense to be configurable, because it should no be allowed that somebody changes the source API for the REST to `graphql`.. Adding a new value is another issue and quite complicated at the moment..

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java (hunk 3 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:35]: Don't get this, this is a constructor, called only one time during init? Does exactly that by creating a single instance of the default metadata..

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/StargateBridgeInterceptor.java (hunk 4 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/StargateBridgeInterceptor.java:45]: Yup, at least sending the default metadata..

File: apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java (hunk 5 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java:31]: But what would we gain with this? This was made so we can start the commons context in the tests, basically it's not used nor asserted anywhere..

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java (hunk 8 above)
Comment (ivansenic) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java:29]: OK.

1. Renaming this to `@SourceApiQualifier`, because it is a `Qualifier`
2. Added https://github.com/stargate/stargate/issues/2195 to remove from schema auth

File: authnz/src/main/java/io/stargate/auth/SourceAPI.java (hunk 10 above)
Comment (ivansenic) [reply authnz/src/main/java/io/stargate/auth/SourceAPI.java]: Because source api has the field `name` that I am comparing to, would not work..

File: apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java (hunk 1 above)
Comment (ivansenic) [reply apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java:30]: See comment above..

Comment (tatu-at-datastax) [reply apis/sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/SourceApiConfiguration.java:30]: (note: nope, since there's no matching Enum entry -- Docs API just uses REST API authz rights)

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java (hunk 3 above)
Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:35]: @ivansenic Ok sorry. Missed that context. N/m.

File: apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java (hunk 5 above)
Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/test/java/io/stargate/sgv2/SourceApiTestConfiguration.java:31]: I was thinking it'd avoid test accidentally passing. If and when not tested yeah never mind.

And since we'd need matching Enum (which I did not realize when adding this comment) not worth it either.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java (hunk 8 above)
Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/SourceApi.java]: Cool, makes sense.

File: authnz/src/main/java/io/stargate/auth/SourceAPI.java (hunk 10 above)
Comment (tatu-at-datastax) [reply authnz/src/main/java/io/stargate/auth/SourceAPI.java]: Ah. True.

File: apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java (hunk 2 above)
Comment (tatu-at-datastax) [reply apis/sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/GrpcMetadataResolver.java:25]: Yeah, sorry, should have removed comment after I realized complexity of enum mapping etc.
You are absolutely right.
There is the bigger question on extensibility, but this PR is not the place for that.
