### PR TITLE
Determine CODACY_REPORTER_VERSION once per test execution

### LINKED ISSUE #652: Sporadic (but frequent) Codacy Coverage Reporter error in CI: SSL_ERROR_SYSCALL in connection to api.bintray.com
Step #5 - "dse-6.8": #=#=#                                                                         ^M######################################################################## 100.0%
    Step #5 - "dse-6.8":  ESC[0;36m--> ESC[0;90mCodacy reporter codacy-coverage-reporter-linux already in cacheESC[0m
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.166Z  info [ConfigurationRules] API base URL: https://api.codacy.com  - (ConfigurationRules.scala:86)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.166Z  info [ReportRules] Parsing coverage data from: /tmp/dse-6.8/./restapi/target/site/jacoco-ut/jacoco.xml ...  - (ReportRules.scala:43)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.286Z  info [ReportRules] Coverage parser used is com.codacy.parsers.implementation.JacocoParser$@91caf2c  - (ReportRules.scala:48)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.293Z  info [ReportRules] Generated coverage report: /tmp/codacy-coverage-11892710142609965930.json (37.41 kB)  - (ReportRules.scala:243)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.293Z  info [ReportRules] Uploading coverage data...  - (ReportRules.scala:244)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.526Z  info [ReportRules] Coverage data uploaded. Coverage received successfully.  - (ReportRules.scala:158)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.526Z  info [ReportRules] 
    Step #5 - "dse-6.8": To complete the reporting process, call coverage-reporter with the final flag.
    Step #5 - "dse-6.8":  Check https://docs.codacy.com/coverage-reporter/adding-coverage-to-your-repository/#multiple-reports
    Step #5 - "dse-6.8":  for more information.  - (ReportRules.scala:80)
    Step #5 - "dse-6.8": 2021-02-08 19:18:37.526Z  info [CodacyCoverageReporter] All coverage data uploaded.  - (CodacyCoverageReporter.scala:22)
    Step #5 - "dse-6.8": 
    Step #5 - "dse-6.8":  ESC[0;32m--> ESC[0;90mSucceeded!ESC[0m
    Step #5 - "dse-6.8":      ______          __
    Step #5 - "dse-6.8":     / ____/___  ____/ /___ ________  __
    Step #5 - "dse-6.8":    / /   / __ \/ __  / __ `/ ___/ / / /
    Step #5 - "dse-6.8":   / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
    Step #5 - "dse-6.8":   \____/\____/\__,_/\__,_/\___/\__, /
    Step #5 - "dse-6.8":                               /____/
    Step #5 - "dse-6.8": 
    Step #5 - "dse-6.8":   Codacy Coverage Reporter
    Step #5 - "dse-6.8": 
    Step #5 - "dse-6.8": 
    Step #5 - "dse-6.8": curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.bintray.com:443 
    Step #5 - "dse-6.8":  ESC[0;36m--> ESC[0;90mDownloading the codacy reporter codacy-coverage-reporter-linux... ()ESC[0m
    Step #5 - "dse-6.8": #=#=#                                                                         ^M##O#- #                                                                       ^M##O=#  #                                                                      
    Step #5 - "dse-6.8": /home/ubuntu/.cache/codacy/coverage-reporter//codacy-coverage-reporter: line 1: The: command not found
    Step #5 - "dse-6.8": 
    Step #5 - "dse-6.8":  ESC[0;31m--> ESC[0;90mFailed!ESC[0m
    Finished Step #5 - "dse-6.8"Previous command invocations successfully check the API version and donwload the tool, but the last command fails in `curl`.

It looks like API throttling or some other access check on the Codacy side.

### PR DESCRIPTION
**Pull request by dimas-b**
Closes #652

### CODE REVIEW

File: ci/test.sh [hunk 1]
```diff
@@ -53,6 +53,10 @@ echoinfo "Test complete"
 
 echoinfo "Uploading test results"
 
+# Determine CODACY_REPORTER_VERSION once to avoid hitting the "get latest" API too frequently
```
Comment (dougwettlaufer) [inline ci/test.sh:56]: Doesn't `get.sh` cache everything after the first call?

File: ci/test.sh [hunk 2]
```diff
@@ -53,6 +53,10 @@ echoinfo "Test complete"
...
+# in the get.sh commands below. Note: the sed command was copied from get.sh
+export CODACY_REPORTER_VERSION="$(curl https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | sed -e 's/.*name[^0-9]*\([0-9]\{1,\}[.][0-9]\{1,\}[.][0-9]\{1,\}\).*/\1/' )"
```
Comment (dougwettlaufer) [inline ci/test.sh:58]: Could we just set this to `latest`?
https://github.com/codacy/codacy-coverage-reporter/commit/10a9742490a7558e43839b253285ae2f64e7e435

**Review by dougwettlaufer — APPROVED** [review]

File: ci/test.sh (hunk 1 above)
Comment (dimas-b) [reply ci/test.sh:56]: It caches the actual reporter code, but it hits the "get latest version" URL on every invocation. I suspect it causes API throttling of something to that effect.
