### PR TITLE
Handle where with  using types other than text fixes #887

### LINKED ISSUE #887: Unable to use "$in" with timestamp field
Given a table with a timestamp column, this request currently fails

```sh
localhost:8082/v2/keyspaces/testks/foo?where={"id": {"$eq":"454674e1-571d-45bc-bd46-be6e9b6165ed"}, "created": {"$in": ["2021-04-21T18:42:22.139Z"]}}
```

The reason for this is that no matter what the array for the `IN` condition is being treated as an array of Strings. Instead we need to convert to an array of whatever the type is for that column.

### PR DESCRIPTION
**Pull request by dougwettlaufer**
Fixes #887

### CODE REVIEW

**Review by ivansenic — APPROVED** [review]
Nice fix :+1:

File: restapi/src/test/java/io/stargate/web/resources/WhereParserTest.java [hunk 1]
```diff
@@ -288,4 +308,24 @@ public void testInOperation() throws IOException {
...
     assertThat(where).isEqualTo(whereExpected);
   }
+
+  @Test
+  public void testInWithTimestampOperation() throws IOException {
+    String whereParam = "{\"created\":{\"$in\":[\"2021-04-23T18:42:22.139Z\"]}}";
+    List<BuiltCondition> whereExpected =
+        singletonList(
+            BuiltCondition.of(
+                "created", Predicate.IN, singletonList(Instant.parse("2021-04-23T18:42:22.139Z"))));
```
Comment (eribeiro) [inline restapi/src/test/java/io/stargate/web/resources/WhereParserTest.java:318]: nit: maybe use `Converters.toCqlValue(type, object)` instead of directly calling `Instant`?

**Review by mpenick — APPROVED** [review]
