### PR TITLE
closes #1887: fixed consistency for reads, added consistency checks in tests

### LINKED ISSUE #1887: QueryExecutor in V2 should use the configured consistency level
Should be attach to all queries automatically.

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Ensures read consistency is used in the `QueryExecutor`. Improves testing in the area, by extending support in the `ValidatingStargateBridge`.  

In addition adds span annotations to the read bridge service and improves the java docs.

**Which issue(s) this PR fixes**:
Fixes #1887 

**Checklist**
- [x] Automated Tests added/updated

### CODE REVIEW

File: sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/service/query/executor/QueryExecutor.java [hunk 1]
```diff
@@ -345,9 +352,17 @@ private Multi<QueryOuterClass.ResultSet> executeQuery(
...
+              // 1. read consistency
+              // 2. needed page size
+              // 3. enriched always
+              // 4. resume mode if defined
+              QueryOuterClass.Consistency consistency = queriesConfig.consistency().reads();
+              QueryOuterClass.ConsistencyValue.Builder consistencyValue =
+                  QueryOuterClass.ConsistencyValue.newBuilder().setValue(consistency);
               QueryOuterClass.QueryParameters.Builder params =
                   QueryOuterClass.QueryParameters.newBuilder()
+                      .setConsistency(consistencyValue)
```
Comment (EricBorczuk) [inline sgv2-docsapi/src/main/java/io/stargate/sgv2/docsapi/service/query/executor/QueryExecutor.java:365]: :+1:

**Review by EricBorczuk — APPROVED** [review]
